### PR TITLE
Use upstream jrick/bitset

### PR DESCRIPTION
**Pull request by dajohi**
... since no local changes exist.

### CODE REVIEW

**Comment by xaur** [comment]
@davecgh it is strange because in [btcsuite](https://github.com/btcsuite) I see several local ("vendored", right?) forks of dependencies that ensure the build will never fail.

Forking dependencies is a good practice for any non-toy project IMO. One [leftpad](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/) was enough ;)

**Comment by jrick** [comment]
@xaur in Go, two identical packages that are otherwise only named differently are treated as two distinct packages by the compiler.  This makes github.com/decred/bitset a functionally different from and incompatible with github.com/jrick/bitset.  If both are imported, it causes code bloat because the same code will appear twice in the binary, so it's better to use a single canonical name for the package.  In addition, if a repo is forked with the intention of using the forked package name, all imports to the package must be rewritten to use the new name.  This can be burdensome when merging upstream updates from the package since now you must deal with merge conflicts.

I'm not concerned with repos disappearing (even other repos that I don't maintain) because all of the developers have local copies of this code and we can reinstate the repo at any point if it must be.

**Comment by dajohi** [comment]
My reasons:

1. Import directly - gives author credit and shows up on their ?importers
2. Staying in sync goes stale so bug fixes and optimizations in later upstream code is missed.
3. Fewer repos for maintaining.

**Comment by xaur** [comment]
Thanks for explaining!

**Pull request merged**
