### PR TITLE
rpcserver:  cache the results of getcoinsupply

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by alexlyp** [comment]
ntACK

**Comment by jcvernaleo** [comment]
jcv@triforce ~ $ dcrctl --testnet -u u -P p getcoinsupply
{
  "coinsupply": 41858012595385
}
jcv@triforce ~ $ dcrctl --testnet -u u -P p getcoinsupply
41858012595385

Looks like the cached return is different than the return at first startup.  I know issue #33 requests we change to a raw number but either way, the cached result needs to be the same as fresh result.  If you want a PR to fix #33 first that's fine or if you want to make the cached result match the current result that is fine too but either way, it needs to match before it goes in.

**Comment by dajohi** [comment]
good catch.

**Comment by jcvernaleo** [comment]
Apparently we are waiting for #36 to go in, then this will need a rebase, then in it will go.

**Comment by jcvernaleo** [comment]
OK

**Pull request merged**
