### PR TITLE
Implement isStakeSuperMajority and RPC bits to interrogate stake versions

### PR DESCRIPTION
**Pull request by marcopeereboom**
Add isStakeSuperMajority functionality and RPC interrogation functions to support soft forking.

Fixes part of #454

### CODE REVIEW

**Comment by jolan** [comment]
Oops typoed the issue number in my PR.

**Comment by davecgh** [comment]
Per IRC conversation, this should only skip 1 period at the beginning so it is consistent with all intervals and a testnet reset will not cause a "phantom" delay.

**Comment by marcopeereboom** [comment]
Here are the test results:
[testresults.txt](https://github.com/decred/dcrd/files/659604/testresults.txt)

**Comment by marcopeereboom** [comment]
This PR is no longer valid.  It has been pulled apart as:
#522 
#524 
#526

**Pull request closed without merging**
