### PR TITLE
Live ticket pool dump

### PR DESCRIPTION
**Pull request by chappjc**
This is for evaluation of the ticket pool data from dcrdata w/ https://github.com/dcrdata/dcrdata/pull/315

@marcopeereboom ^^^

I think this is just for discussion, no intent to merge AFAIK

### CODE REVIEW

**Comment by davecgh** [comment]
NACK.  I don't want block connection writing a bunch of extra data to disk.  Especially using JSON.

**Comment by chappjc** [comment]
Oh no doubt!  This code has no place in production, OMG.  :). Marco wanted a PR to reference for some stuff we're working on.  This is 200% hackalicious

**Comment by davecgh** [comment]
Oh, I missed that you said just for discussion.

**Comment by davecgh** [comment]
Going to close this, it's still in history for discussion purposes.

**Pull request closed without merging**
