### PR TITLE
docs: Major update to home README

### LINKED ISSUE #251: Update the readme and other docs
The readme and many other documents still discuss Bitcoin and Bitcoin related features. They should be updated for relevance to Decred.

### PR DESCRIPTION
**Pull request by alexlyp**
Partially fixes #251

### CODE REVIEW

**Comment by jcvernaleo** [comment]
OK

**Comment by cjepson** [comment]
The build from source instructions should still be included. I think there should be a new section like "Binaries" that offers the links to the docs, since the docs do not instruct on how to build from source.

**Comment by cjepson** [comment]
Needs to be rebased and updated with proper glide building from source instructions.

**Comment by jcvernaleo** [comment]
OK

**Pull request merged**
