### PR TITLE
Clean up and fix fallthrough on invalid tx types for getrawmempool rpc request

### LINKED ISSUE #110: getrawmempool takes invalid input
'getrawmempool false blah'  will return all.  Should return an error instead.

### PR DESCRIPTION
**Pull request by alexlyp**
Fixes #110

### CODE REVIEW

**Comment by cjepson** [comment]
utACK

**Comment by jcvernaleo** [comment]
It does correctly give an error on bogus tx type and is okay with either no args or verbose=false.  But verbose=true panics:
jcv@triforce tmp $ dcrctl --testnet --wallet getrawmempool true
-4: the client has been disconnected

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4882ef]

goroutine 98 [running]:
panic(0xc4aa00, 0xc8200101e0)
        /home/jcv/code/golang/src/runtime/panic.go:464 +0x3e6
main.handleGetRawMempool(0xc82a351a40, 0xacd000, 0xc82dc5acc0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/jcv/code/go/src/github.com/decred/dcrd/rpcserver.go:3396 +0xaef
main.(*rpcServer).standardCmdResult(0xc82a351a40, 0xc830888840, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/jcv/code/go/src/github.com/decred/dcrd/rpcserver.go:4900 +0xc0
main.(*wsClient).handleMessage(0xc8201603f0, 0xc82f36cc00, 0x44, 0x600)
        /home/jcv/code/go/src/github.com/decred/dcrd/rpcwebsocket.go:1437 +0x1577
main.(*wsClient).inHandler(0xc8201603f0)
        /home/jcv/code/go/src/github.com/decred/dcrd/rpcwebsocket.go:1482 +0x3e3
created by main.(*wsClient).Start
        /home/jcv/code/go/src/github.com/decred/dcrd/rpcwebsocket.go:1767 +0x149
jcv@triforce tmp $

**Comment by jcvernaleo** [comment]
Also, maybe the help text should list the allowed tx types rather than just:
2. txtype  (string, optional)                 Type of tx to return.

**Comment by jcvernaleo** [comment]
Looks good now.  Will merge if travis ever finishes.
tACK

**Pull request merged**
