### PR TITLE
Rename one of the testnet seeders.

### PR DESCRIPTION
**Pull request by jcvernaleo**
Switched the testnet seeder on netpurgatory to .com instead
of .org so it matches the mainnet one.

I'm consolidating/reorganizing some servers and domains so I'd like to move my testnet seeder to the same domain as my mainnet one.

### CODE REVIEW

**Comment by jcvernaleo** [comment]
Just to note since I have this on one box, I can only run one at a time so I won't change the domain of the seeder itself until this gets an okay.  Doesn't matter too much since it is testnet though.

**Comment by dajohi** [comment]
@jcvernaleo are you able to keep the .org working til next release.  not sure if a cname from the .org to .com would work to keep old clients working...

**Comment by jcvernaleo** [comment]
@dajohi I can switch it over whenever you want.  Doesn't have to be now.  The only thing that would be a pain would be running both the .com and the .org at the same time.

**Comment by jcvernaleo** [comment]
If you want I'm happy for this PR to sit until just before the next release even.

**Comment by dajohi** [comment]
as a test:
setup .com
set ttl for the .org to 60 seconds.  cname it to .com and see if it still works...
if not, switch it back.. should only be in caches for 60 seconds at most..

**Comment by jcvernaleo** [comment]
How would that work?  It is an NS record for the seeder.  Would that even play nice with a CNAME?

**Comment by dajohi** [comment]
coordinate with @jcvernaleo right before next release.

**Comment by jcvernaleo** [comment]
@jolan done.

**Pull request merged**
