### PR TITLE
Add estimatestakediff RPC command

### PR DESCRIPTION
**Pull request by cjepson**
The new RPC command estimatestakediff was added. It estimates the
minimum and maximum next stake difficulty. The caller can also
estimate a new difficulty given a passed number of tickets to be
mined in the remaining difficulty period.

### CODE REVIEW

**Comment by alexlyp** [comment]
tACK, 

Though I'd prefer the command option for tickets to be per block 0-20 instead of some number 0-2880 depending on how long it is until the next retarget

**Comment by cjepson** [comment]
That doesn't give you fine-tune granularity. It would only give you 144*5, 144*6... etc

**Comment by raedah** [comment]
Thx, this should be able to close https://github.com/decred/dcrd/issues/134

But I think right now its missing an important equation.
perc_full = ticket_purchases_so_far_this_stake_period / (blocks_so_far_this_stake_period * 20)
best_estimate_tickets = 2880 * perc_full
Show this as "estimatestakediffresult-best":  "Best estimate for stake difficulty"

**Comment by cjepson** [comment]
Sorry, I added the feature after jy-p prodded and called it 'expected' before seeing your comment. Will leave it as is, but yes, now it gives min, max, and expected.

**Comment by alexlyp** [comment]
cool expected looks good.  tACK

**Pull request merged**
