### PR TITLE
Do not error if dcrctl can't find dcrd.conf.

### LINKED ISSUE #303: dcrctl complains about not finding dcrd.conf when creating default config file
But I don't have a dcrd.conf and I don't want a dcrctl.conf to be generated anyway.  dcrctl gives this every command, even though everything is working:

    Error creating a default config file: open C:\Users\u\AppData\Local\Dcrd\dcrd.conf: The system cannot find the file specified.

This message should perhaps be at debug level.

### PR DESCRIPTION
**Pull request by jcvernaleo**
Closes #303

### CODE REVIEW

**Comment by alexlyp** [comment]
tACK

**Comment by jolan** [comment]
Missing closing parenthesis in comment but OK otherwise

**Comment by marcopeereboom** [comment]
What @jolan said.

**Comment by jcvernaleo** [comment]
Comment fixed.

**Comment by marcopeereboom** [comment]
ok

**Pull request merged**
