### PR TITLE
mempool: Move to internal.

### PR DESCRIPTION
**Pull request by davecgh**
**This requires #2273**.

This makes the `mempool` an internal package such that it will no longer be an exported module.  The only place its functionality is really needed is for the internal implementation of dcrd itself and thus having an unnecessary exported module significantly increases the maintenance burden.

This is part of the overall effort to reduce the total number of modules and eventually get to the point it will be possible to follow semver for the root module.

It is worth noting that there are a few constants, which will be listed below, that were exported from this module that callers might have previously relied upon.  However, due to previous discussions about the goal of removing the module, a code search has revealed that there are no known callers that still rely on them.

The aforementioned constants are:

- `MaxStandardTxSize`
- `DefaultMinRelayTxFee`
- `BaseStandardVerifyFlags`

Overview of the major changes:

- Move the following files from `mempool` -> `internal/mempool`:
  - `README.md`
  - `doc.go`
  - `error.go`
  - `log.go`
  - `mempool.go`
  - `mempool_test.go`
  - `policy.go`
  - `policy_test.go`
- Remove `mempool/go.mod` and `mempool/go.sum`
- Make the `README.md` and `doc.go` files match the new reality
- Update all import paths in the repository accordingly
- Remove the dependency from the root `go.mod`
- Run `go mod tidy` on all modules
- Update project docs for removal of the module.

### CODE REVIEW

**Comment by davecgh** [comment]
Rebased and fixed the commit typo pointed out by @rstaudt2.

**Comment by JoeGruffins** [comment]
At the end of the file at ` dcrd/mempool/README.md ` There is a section `Installation and Updating` that should be removed or changed to say somethig like `This package is internal and therefore is neither directly installed nor needs to be manually updated.`.

**Comment by JoeGruffins** [comment]
Not completely sure, but in the comment message `This is part of the overall effort to reduce the total number of modules
and eventually get to the point it will be possible to follow semver for the root module.` I think needs to be `... get to the point **where** it will be ...`

**Comment by davecgh** [comment]
@JoeGruffins Regarding the `README.md`, good catch.  I did that for the mining one, but forgot for mempool.  Updated.

**Pull request merged**
