### PR TITLE
multi: Remove rpctest package

### PR DESCRIPTION
**Pull request by matheusd**
This moves the existing tests that rely on the existing `rpctest` package to a new internal `integration/rpctests` package, switches them to use the recently introduced `dcrtest/dcrdtest` package and finally removes the `rpctest` package from this repository.

### CODE REVIEW

**Comment by dnldd** [comment]
Looks great 👍

**Review by dnldd — APPROVED** [review]

**Review by davecgh — COMMENTED** [review]
Looks great overall thus far, but I did notice that it needs to run `go mod tidy` because `hdkeychain` is no longer a direct dependency.

**Review by davecgh — APPROVED** [review]
Very nice work on this and getting the RPC testing framework all split out and updated to improve some of its warts.

I ran the relevant affected tests on both a Linux and Windows environment:
```
$ go test ./internal/rpcserver
ok      github.com/decred/dcrd/internal/rpcserver       5.628s

$ go test -tags rpctest ./internal/integration/rpctests
ok      github.com/decred/dcrd/internal/integration/rpctests    53.963s
```

I also confirmed that it is in fact building the most recent dcrd code before running the tests by both manually examining the built binary in the temp dir and also by intentionally breaking an RPC handler:
``` 
$ go test -tags rpctest  -run=TestRpcServer ./internal/integration/rpctests
--- FAIL: TestRpcServer (2.80s)
    rpcserver_test.go:41: Block hashes do not match. Returned hash 0000000000000000000000000000000000000000000000000000000000000000, wanted hash 008e857ca0493162baf6c7f9261a253bec65cda771d75c09ed3dc309da66a7ab
FAIL
FAIL    github.com/decred/dcrd/internal/integration/rpctests    2.920s
FAIL
```

I'm going to go ahead and approve, but as mentioned, it does still need a `go mod tidy` before merge.

**Comment by matheusd** [comment]
Tidied and rebased against latest master

**Pull request merged**
