### PR TITLE
txscript: Prepare v4.0.0.

### PR DESCRIPTION
**Pull request by davecgh**
**This requires #2816**.

This updates the `txscript` module dependencies, the copyright year in the files modified since the previous release, and serves as a base for `txscript/v4.0.0`.

The updated direct dependencies in this commit are as follows:

- github.com/decred/dcrd/chaincfg/chainhash@v1.0.3
- github.com/decred/dcrd/chaincfg/v3@v3.1.0
- github.com/decred/dcrd/dcrec/edwards/v2@v2.0.2
- github.com/decred/dcrd/dcrec/secp256k1/v4@v4.0.1
- github.com/decred/dcrd/wire@v1.5.0
- github.com/decred/slog@v1.2.0

The full list of updated direct dependencies since the previous `txscript/v3.0.0` release are as follows:

- github.com/dchest/siphash@v1.2.2
- github.com/decred/base58@v1.0.3
- github.com/decred/dcrd/chaincfg/chainhash@v1.0.3
- github.com/decred/dcrd/chaincfg/v3@v3.1.0
- github.com/decred/dcrd/crypto/blake256@v1.0.0
- github.com/decred/dcrd/dcrec/edwards/v2@v2.0.2
- github.com/decred/dcrd/dcrec/secp256k1/v4@v4.0.1
- github.com/decred/dcrd/wire@v1.5.0
- github.com/decred/slog@v1.2.0

The following direct dependencies are no longer required as compared to the previous `txscript/v3.0.0` release:

- github.com/decred/dcrd/dcrutil/v3

Finally, all modules in the repository that depend on `txscript` are tidied to ensure they are updated to use the latest versions hoisted forward as a result.

### CODE REVIEW

**Review by chappjc — APPROVED** [review]

**Comment by chappjc** [comment]
Thoughts about this for scriptv0.go?

```go
func ExtractStakeScriptHashV0(script []byte) []byte {
	scriptType := DetermineScriptTypeV0(script)
	switch scriptType {
	case STStakeSubmissionScriptHash, STStakeGenScriptHash,
		STStakeRevocationScriptHash, STStakeChangeScriptHash,
		STTreasuryGenScriptHash:

		return txscript.ExtractScriptHash(script[1:])
	}

	return nil
}
```

**Comment by davecgh** [comment]
There is `ExtractStakeSubmissionScriptHashV0`, `ExtractStakeGenScriptHashV0`, etc.  I guess you're just asking for a consolidated one that is "give me a script hash if the script is any of the supported standard stake outputs?

I'm not opposed to that if so.  I wouldn't quite implement it that way, since there is already an unexported helper `func extractStakeScriptHashV0(script []byte, stakeOpcode byte) []byte {` that is used by the others.  I would say if that's added, the same should be done for `ExtractStakePubKeyHashV0` too.

**Comment by chappjc** [comment]
That's the idea.  Regarding the unexported helper, I noticed that and was going to suggest a different implementation that switched on each `STStage*ScriptHash` type and passed the appropriate opcode, however, because in the above suggestion passes through `DetermineScriptTypeV0` first, it would be safe to just skip the first byte.

**Comment by davecgh** [comment]
I'll open a PR in a bit and rebase this on one top so it ends up available in the release tag.

**Review by rstaudt2 — APPROVED** [review]

**Review by chappjc — APPROVED** [review]

**Pull request merged**
