### PR TITLE
[release-v1.7] multi: Build and doco updates for Go 1.20. 

### PR DESCRIPTION
**Pull request by davecgh**
This is a backport of #2976, #3021 and #3052 to the 1.7 release branch.

### CODE REVIEW

**Review by chappjc — APPROVED** [review]
That's a lotta gofmt, but lgtm.

Do we cut the year out of the copyright at some point?  I'm not sure what it really conveys.

**Comment by davecgh** [comment]
I'm still working on making it build properly against the latest versions of Go and the linter/vet that works with them.  The updates to various things are spread out over time, so having to find and cherry-pick the right ones.

> Do we cut the year out of the copyright at some point? I'm not sure what it really conveys.

I think that's only because these are all backports to an old release branch.  On `master` they show clearly when the last time the code was updated by the project and is covered by the copyright.  This matters when code gets copied all over the place over time and updated.

**Comment by davecgh** [comment]
Alright, I've cherry-picked and backported everything for the 1.7 release branch to build with the latest versions of Go and pass all lint and vet checks now.

**Review by jrick — APPROVED** [review]
looks fine

**Pull request merged**
