### PR TITLE
gencerts: Add certificate authority capabilities

### PR DESCRIPTION
**Pull request by jrick**
This commit adds the ability to generate certificates signed by a
local CA cert and key.  The -C and -K flags are used to provide the
filepaths to the certificate and key files, respectively.

For simplicity and security, the issued certificate is not able to act
as an intermediate certificate, and thus cannot sign other
certificates to trust.  More advanced usage is still possible using
external tooling (e.g. openssl), but is not provided by gencerts.

Acting as your own Certificate Authority can reduce configuration
complexity by allowing each of your clients to only trust a single CA
certificate that you control, rather than juggling many different
autogenerated certificates for every different server.

### CODE REVIEW

**Comment by jrick** [comment]
This shell session shows how gencerts can be used to create a certificate authority, and from that CA, issue RPC certificates and keys for dcrd and dcrwallet.  The same dcrctl config (referencing the exact same CA certificate as the trusted root) is able to communicate with both servers, with only an additional --wallet flag.

```
$ cd /tmp/gencerts
$ mkdir {dcrd,dcrwallet,dcrctl}
$ gencerts ca-cert.pem ca-key.pem
$ gencerts -C ca-cert.pem -K ca-key.pem -L dcrd/rpc.{cert,key}
$ gencerts -C ca-cert.pem -K ca-key.pem -L dcrwallet/rpc.{cert,key}
$ cp dcrd/rpc.cert dcrwallet/dcrd.cert
$ cat >dcrd/dcrd.conf <<EOF
> rpcuser=user
> rpcpass=pass
> testnet=1
> EOF
$ cat >dcrwallet/dcrwallet.conf <<EOF
> username=user
> password=pass
> testnet=1
> pass=pass
> EOF
$ cat >dcrctl.conf <<EOF
> rpcuser=user
> rpcpass=pass
> rpccert=/tmp/gencerts/ca-cert.pem
> testnet=1
> EOF
$ dcrd -A ./dcrd >/dev/null &
[1] 18995
$ echo "yes\nno\nno\nOK" | dcrwallet -A ./dcrwallet --create >/dev/null
$ dcrwallet -A ./dcrwallet >/dev/null &
[2] 4050
$ dcrctl -C dcrctl.conf getinfo
{
  "version": 1070000,
  "protocolversion": 8,
  "blocks": 4583,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 29356.61246335,
  "testnet": true,
  "relayfee": 0.0001,
  "errors": "",
  "addrindex": false,
  "txindex": false
}
$ dcrctl -C dcrctl.conf --wallet getinfo
{
  "version": 1070000,
  "protocolversion": 8,
  "walletversion": 1060000,
  "balance": 0,
  "blocks": 5076,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 13953.954988937297,
  "testnet": true,
  "keypoololdest": 0,
  "keypoolsize": 0,
  "unlocked_until": 0,
  "paytxfee": 0.0001,
  "relayfee": 0.0001,
  "errors": ""
}
```

Usually this sort of setup is not too painful with all local daemons, because dcrctl will by default try to reach into the default dcrd and dcrwallet application data directories to find the certificate.  However, this method stops working well once remote servers are involved.  For this case, the -H flag should be used to provide the hostname or IP address of the remote server that dcrd/dcrwallet will listen on.  dcrctl will not need any more configuration changes other than providing the server address (`-s <hostname_or_ip>`) and possibly also the --wallet flag to swap default ports.  The same CA cert can be trusted to communicate with any server as long as the generated issued certificate and key were copied over to the remote server for dcrd/dcrwallet to use.

**Review by davecgh — COMMENTED** [review]
Code looks fine.  I want to test it before merging though.

**Review by davecgh — CHANGES_REQUESTED** [review]
The handling of `-C` and `-K` behave a bit strange:

```sh
$ gencerts -C ca-cert.pem -L rpc.{cert,key}
open CA keypair: open : The system cannot find the file specified.
$ gencerts.exe -K ca-key.pem -L rpc.{cert,key}
```

Notice in the first case that failing to specify `-K` doesn't result in an error that the required parameter wasn't specified as expected, and instead gives an error that would lead the user to believe it was `ca-cert.pem` that couldn't be opened instead of the fact it's really the missing key. 

Then, in the second case, not specifying `-C` with `-K` results in creating an ordinary cert pair without any signature or error.

Both of these cases can be handled by throwing a nice error when either `-C` is specified and `-K` is not, or vice versa.

**Review by davecgh — APPROVED** [review]
Looks good now.  Just needs to be squashed.

**Pull request merged**
