### PR TITLE
release: Bump for 2.0 release cycle.

### PR DESCRIPTION
**Pull request by davecgh**
The upcoming release will be version 2.0.0, so this bumps the development version accordingly.

### CODE REVIEW

**Comment by matthawkins90** [comment]
Previous dcrd hardforks have only incremented the minor version number. Is there a reason you're planning for 2.0.0 instead of 1.10.0 after 1.9.x?

**Comment by davecgh** [comment]
There will not be a 1.9.0 release.  It will be 2.0.0 instead.  This is bumping in anticipation of that.

**Comment by jrick** [comment]
no, api changes don't affect the user-facing version we give to the software. they are decoupled specifically so we can make major module changes without changing our "decred version" (which is shared among all of our core software products), and vice-versa (as seen here).

the decision to use 2.0.0 is arbitrary.

**Comment by jrick** [comment]
(and there was no breaking wire changes between tagged releases of the wire module, only between prerelease untagged versions of wire)

**Review by jrick — APPROVED** [review]
meant to ok this

**Review by matthawkins90 — APPROVED** [review]

**Review by dajohi — APPROVED** [review]

**Pull request merged**
