### PR TITLE
Remove a bunch of dead code.

### LINKED ISSUE #442: blockchain: Remove/Move Debug* from common.go
These functions do not belong in production code.

Personally, I think it is much easier to use a tool like spew to dynamically dump the information versus manually updating debug functions that will surely get out of date as data structures change.

That said, even if these functions are preferred over a dynamic dump, they most definitely should only be in `*_test.go` files so they are not compiled into production code.

### PR DESCRIPTION
**Pull request by marcopeereboom**
The one function used in common.go was replaced with spew and do some additional cleanup while here.

Fixes #442

### CODE REVIEW

**Comment by jrick** [comment]
While i love the code removal i don't like introducing spew, that is a debug tool and i don't want it in our production binaries.

**Comment by davecgh** [comment]
I'm not sure whether or not spew should be used in this PR as I haven't looked, but it is already used elsewhere and vendored via `glide.yaml`, so it wouldn't be introducing a new dependency.

**Comment by marcopeereboom** [comment]
@jrick even though I appreciate your comment and the idea I think that this is the exception to the rule.  In this case, there is a much larger chance of the struct changing without editing the corresponding debug function and therefore spew is the next best thing.

**Comment by jcvernaleo** [comment]
If the struct changes, why wouldn't we also change the debug function?  It seems like that is what we would do in every other case.

**Comment by marcopeereboom** [comment]
I removed spew despite y'all being wrong :-)

**Pull request merged**
