### PR TITLE
blockchain: allow ticket purchases included in the same block

### PR DESCRIPTION
**Pull request by tuxcanfly**
Refs #120 

Note: Testing this, not yet ready for review.

### CODE REVIEW

**Comment by cjepson** [comment]
This PR can never work I think, the tx tree regular is not spendable from in the tx tree stake until the next block because of validation rules. It will never be the case that you can purchase tickets with a transaction from tx tree regular in the same block because those UTXOs do not exist until the stakeholders validate them.

**Comment by cjepson** [comment]
Also this issue I believe is fixed by a recent PR by me/davec.

https://github.com/btcsuite/btcd/pull/692

Just never got around to cleaning it up and testing davec's code.

**Comment by marcopeereboom** [comment]
What is the status on this?

**Comment by tuxcanfly** [comment]
Closing this in favor of the patch proposed in [btcsuite/btcd#692](https://github.com/btcsuite/btcd/pull/692) as mentioned above.

**Pull request closed without merging**
