### PR TITLE
dcrjson: Add create unsigned transaction command

### PR DESCRIPTION
**Pull request by vctt94**
This PR is related with https://github.com/decred/dcrwallet/pull/1180

### CODE REVIEW

**Comment by davecgh** [comment]
Why is this being introduced?  There is already `createrawtransaction` which serves the purpose of creating an unsigned transaction.

**Comment by vctt94** [comment]
So instead of add `createunsignedtransaction`, should I create the rpc command using the `createrawtransaction` and only make changes on the dcrwallet?

**Comment by vctt94** [comment]
I am not sure as well. It is an open issue at dcrwallet https://github.com/decred/dcrwallet/issues/111 and @jrick suggested to add the ability to create unsigned transactions as a rpc command.

Maybe to make this process simpler?

**Comment by davecgh** [comment]
For example, here is one paying to the project subsidy:

```bash
$ dcrctl createrawtransaction '[]' '{"Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx":1.3}' > rawtx.hex
$ cat rawtx.hex
01000000000180a4bf0700000000000017a914f5916158e3e2c4551c1796708db8367207ed13bb87000000000000000000
``` 

Now you would take that raw transaction and feed it into wallet:
```bash
$ cat rawtx.hex dcrctl --wallet fundrawtransaction - >f fundedrawtx.hex
```

Finally, sign it:
```base
$ cat fundedrawtx.hex | dcrctl --wallet signrawtransaction -
```

**Comment by jrick** [comment]
Let's drop this and just use createrawtransaction, and rely on fundrawtransaction to perform fee estimation/add a change output.

**Pull request closed without merging**
