### PR TITLE
mining: introduce a block template generator.

### PR DESCRIPTION
**Pull request by teknico**
**This requires PR #910.**

Port over the changes from https://github.com/btcsuite/btcd/pull/810 , see description there. Part of #709.
Extend the `TxSource` interface and move the `VoteTx` type to `blockchain` because it's needed by both `mining` and `mempool`.

TODO - tests fail:
```
--- FAIL: TestHarness (0.86s)
	rpc_harness_test.go:101: unable to get nodeA's peer info
FAIL
FAIL	github.com/decred/dcrd/rpctest	2.745s
```

### CODE REVIEW

**Comment by teknico** [comment]
Rebased on `remove-bmgr-chain-state` and pushed.

**Comment by dajohi** [comment]
@teknico another rebase please.

**Comment by teknico** [comment]
Rebased on master and pushed again.

**Comment by teknico** [comment]
Rebased on `remove-bmgr-chain-state` and pushed again.

**Comment by davecgh** [comment]
Closing since this depends on #910.

**Pull request closed without merging**
