### PR TITLE
Remove --addrindex option.

### LINKED ISSUE #282: dcrd crashes repeatedly
dcrd always crashes right after it starts. Here is the log from nohup.log

https://gist.github.com/gwenphuong/a4f92b55879cbba260b58e5ce9a13221

### PR DESCRIPTION
**Pull request by jcvernaleo**
addrindex does not currently work so do not allow it as an option.
The code for it is still currently there, but no longer hooked in
to something users can set.

Closes #282

### CODE REVIEW

**Comment by cjepson** [comment]
OK

**Comment by jrick** [comment]
I think this still leaves the option around, but just ends up renaming it from --addrindex to --AddrIndex

**Comment by jcvernaleo** [comment]
@jrick doesn't look like it to me:
```
jcv@triforce dcrd $ dcrd --AddrIndex
unknown flag `AddrIndex'
Use dcrd -h to show usage
jcv@triforce dcrd $ dcrd --addrindex
unknown flag `addrindex'
Use dcrd -h to show usage
```

**Comment by jrick** [comment]
alright nvm then, i'm just confused as usual.  ok

**Pull request merged**
