### PR TITLE
Add editorconfig

### PR DESCRIPTION
**Pull request by marcopeereboom**

### CODE REVIEW

**Comment by jrick** [comment]
I think this is absolutely stupid (sorry).  gofmt already covers all of these settings for Go source files, except for the number of spaces used for a tabstop (which makes zero difference in the code we produce).

**Comment by chappjc** [comment]
I prefer 4 spaces per tab.  How come a preference is coded here?

**Comment by jrick** [comment]
Because we have some odd rule (that i tend to ignore in dcrwallet) that all code must fit in a puchcard.


If the number of spaces used in a tab is so important, we should be using spaces not tabs for indentation.  The fact that gofmt chose to use tabs tells me that this is a silly rule to begin with.

**Comment by jrick** [comment]
> Indentation
> We use tabs for indentation and gofmt emits them by default. Use spaces only if you must. 
>
> Line length
> 
> Go has no line length limit. Don't worry about overflowing a punched card. If a line feels too long, wrap it and indent with an extra tab. 

https://golang.org/doc/effective_go.html

**Comment by chappjc** [comment]
Well, I'm certainly in no position to influence your coding standards, but 80 columns often seems to short, while 100 almost always seems too long, IMHO.

I love having tabs in golang source so that it can be displayed any way the editor wants it.  Which is why I'm asking about this commit because it seems to be dictating to the editor how it will appear on my screen.  I don't know what editors support this file, but if vscode is one, I'm not terribly excited about the change.

**Comment by jrick** [comment]
@chappjc you are a valuable member of our coding community, and your voice should absolutely be heard.  Don't let anything else tell you your opinion doesn't matter.

**Comment by davecgh** [comment]
This really isn't the right place to debate the whole 80 col thing, which is long established and simply not worth the effort to rehash over and over again.  I guarantee you that in this very issue there are already 4 people with 4 different opinions on what it should be.  There has to be some limit, and whatever that limit is somebody won't like, so it's just a massive waste of time to debate that.

Anyways, answering the questions with reasons that aren't loaded with a bunch of personal bias, yes vscode does support `.editorconfig`, but you can override it too if you prefer.

The reason for this PR is consistency.  We don't want PRs that end up having diffs that do this:

```Go
			// This is some code that is indented three times along
			// with a comment that wraps at col 80 and a tabstop of
			// 8.
```

Developer 2 comes along and updates the comment and also makes it wrap "properly" according to their editor:

```Go
		// This is some code that is indented three times along with a
		// comment that wraps at col 80 and a tabstop of 4.
```


For the record, I prefer 4 spaces per tab too as I feel like 8 wastes too much horizontal space, but regardless of my personal preference, I would prefer some consistent choice, regardless of what that specific choice is.

**Comment by jrick** [comment]
If the goal is simply consistency, at least use the value that the majority of developers are using.  That value is not 8.

**Comment by marcopeereboom** [comment]
I will get into a fistfight with anyone who argues that tabs are != 8.

**Comment by jrick** [comment]
The whole point of a tab is that you don't have to care what someone else uses, you can set it to whatever the hell you want.

Go recommends tabs.

Therefore the whole point of trying to fit code in a character width limit is ridiculous.

**Pull request closed without merging**
