### PR TITLE
WIP: mining/mempool: Move priority code to mining pkg.

### PR DESCRIPTION
**Pull request by teknico**
**This requires PRs #910, #911 and #912.**

Port over the changes from https://github.com/btcsuite/btcd/pull/813 , see description there. Part of #709.

TODO: tests in `mining/policy_test.go` are failing:

```
--- FAIL: TestCalcPriority (0.00s)
	policy_test.go:164: CalcPriority #0 ("one height 7 input, prio tx height 169"): unexpected priority got 0 want 5e+09
	policy_test.go:164: CalcPriority #1 ("one height 100 input, prio tx height 169"): unexpected priority got 0 want 2.1296296296296296e+09
	policy_test.go:164: CalcPriority #2 ("one height 7 input, prio tx height 100000"): unexpected priority got 0 want 3.0862037037037036e+12
	policy_test.go:164: CalcPriority #3 ("one height 100 input, prio tx height 100000"): unexpected priority got 0 want 3.0833333333333335e+12
FAIL
FAIL	github.com/decred/dcrd/mining	1.857s
```

The call to `utxoView.LookupEntry` in `calcInputValueAge` is always returning `nil`: probably the Bitcoin transaction data need adjustment to work in Decred tests.

### CODE REVIEW

**Comment by dajohi** [comment]
@teknico are you working on fixing the test failures?

**Comment by dajohi** [comment]
Can you make this simple as in ..  1 PR per commit perhaps?

**Comment by teknico** [comment]
Rebased on `introduce-cpuminer-config` and pushed. Going to split this into four PRs, as asked for.

**Comment by davecgh** [comment]
Closing since this depends on #910.

**Pull request closed without merging**
