### PR TITLE
peer: Refactor peer code into its own package.

### PR DESCRIPTION
**Pull request by davecgh**
Contains the following upstream commits:

- 00bddf7540f8aeff7ddea077cf0ce89bc09ea483
- 250228c32f0d84544ca27e654f6ab5ac6fce0ed8
- f1bd2f8d6e52253335578af322d18af3efea9e6b
- cbbe3a8bbe7bcabe7f31883428b619487dfdecdd
- aa03d68e1e2be9f53655cd466edf81c64e573085

In addition to the normal required changes for syncing, the following changes have been made in order to facilitate integration of the new package into Decred:

- Removed check in `PushRejectMsg` against protocol version since all peers since the initial version support it
- Fixed leaked timer in `syncMiningStateAfterSync` function
- Add the Decred-specific `OnGetMiningState` and `OnMiningState` handlers to the new peer package
- Add handler for the new mining state messages to the `serverPeer` type and register them
- Use the new constant for `wire.InitialProtocolVersion` in the reject message instead of hard coded number
- Remove logic specific to the regression network since Decred does not have it

### CODE REVIEW

**Comment by cjepson** [comment]
The new (broken) test in  txscript/data/tx_valid.json should be removed in favour of an actual testing suite in the future.

**Comment by cjepson** [comment]
Seeing tons of these:
`
11:42:39 2016-05-20 [ERR] PEER: Can't read message from 166.78.62.30:9108 (outbound): read tcp x.x.x.x:44676->166.78.62.30:9108: read: connection reset by peer
11:42:39 2016-05-20 [ERR] PEER: Can't send message to 166.78.62.30:9108 (outbound): write tcp x.x.x.x:44676->166.78.62.30:9108: write: broken pipe
`

**Comment by davecgh** [comment]
There is an upcoming commit which stop those read error prints, but there are a couple of commits I wanted to sync via a separate PR first.

**Comment by cjepson** [comment]
OK. Mainnet node is otherwise happy and without issue.

**Comment by alexlyp** [comment]
tACK.  have been running on testnet smoothly for 3+ hours

**Comment by davecgh** [comment]
Removed the `txscript` tests which don't apply.

**Comment by cjepson** [comment]
OK to go in

**Pull request merged**
