### PR TITLE
chaincfg: split params into per-network files.

### PR DESCRIPTION
**Pull request by JFixby**
The purpose of this PR is to reduce the number of code lines in the chaincfg/params.go (from 1262 to 650) improving its readability for future maintenance.

Changes:
 - move variable `MainNetParams` into dedicated file `mainnetparams.go`
 - move variable `TestNetParams` into dedicated file `testnetparams.go`
 - move variable `SimNetParams` into dedicated file `simnetparams.go`

No logical changes were made. Just Cut&Paste.

### CODE REVIEW

**Comment by alexlyp** [comment]
nack

**Comment by JFixby** [comment]
Thank you @davecgh 

Should be good now.
Let me know if I still need to fix something.

**Comment by davecgh** [comment]
The commit title still exceeds the max of 50 chars.  I changed the PR title to one that fits.  I'll still need to review the code to ensure no changes made it in.

**Comment by jrick** [comment]
I'm finding this change quite annoying.  I was previously able to use go-to-reference in my editor to open the parameters file and then search that exact same file for the particular network's parameters I was interested in.  After this change, the actual parameter values are in different files and it takes more effort to find the correct file and parameter definitions.

**Comment by JFixby** [comment]
Is it about the "Find all references"?

image

**Comment by jrick** [comment]
No, i'm talking about go to definition on fields of a params object, not find all references of the defined field.  The latter takes exuberantly long (and it's even faster to find and open the files themselves) because the tooling has to search for any references in my entire GOPATH.

**Comment by JFixby** [comment]
Generally, it is not easy to read a file with 1262 lines of code.
Hard to read correlates with hard to maintain and hard to spot a problem.
Longer files = more bugs. Shorter files = less bugs.

As far as I understand, your case is the following:
You are somewhere in the code and you are looking for the network parameter value assignment.

I may suggest the following solution:
1) click "Jump to declaration/Go to definition" (Ctrl + mouse click)
2) select "Find all references/occurrences/usages" - there you find the assignment and that's it

However, I found that in VSCode IDE it is not that easy.
1) "Go to definition" takes 3-5 seconds, which is abnormally slow. Eclipse IDE was doing it instantly in 2005.
2) "Find all references" takes about 30-60 seconds to perform.

I checked VSCode issue tracker. Both these issues are known and were reported multiple times in there. It seems nobody is interested in fixing it. VSCode devs just keep closing the tickets. 

I checked GoLanD. There I found "Find all references"-feature that does exactly what you need. It instantly returns detailed search results, that will bring you to the exact line of code you look for.

image

**Comment by chappjc** [comment]
I don't see those kinds of slow times.  I do:
- Go to definition (~1 sec).
- Find in all files (CTRL-SHIFT-F, ~1sec).
It's quick, but not as smooth as already having the right file opened after
the first step.

**Comment by JFixby** [comment]
Good. But opening the right file in the first step is not smooth. You still have to call the `CTRL-F` to find the code line you need (value assignment) and scroll over 1200 lines up and down, checking you are actually looking at the right network params set, because there are 3 networks in the same file, it is easy to mix up.

Btw, GoLanD will aid you well. In one single move it will point you directly from usage code to the assignment. After this PR you just need to glance at the file name: is it the `mainnetparams.go` or the `testnetparams.go`

**Pull request merged**
