### PR TITLE
docker: Update image to golang:1.22.2-alpine3.19.

### PR DESCRIPTION
**Pull request by davecgh**
This updates the docker image to golang:1.22.2-alpine3.19.

To confirm the new digest:

```
$ docker pull golang:1.22.2-alpine3.19
1.22.2-alpine3.19: Pulling from library/golang
...
Digest: sha256:cdc86d9f363e8786845bea2040312b4efa321b828acdeb26f393faa864d887b0
...
```

### CODE REVIEW

**Review by ukane-philemon — APPROVED** [review]
LGTM

```
% docker pull golang:1.22.2-alpine3.19
1.22.2-alpine3.19: Pulling from library/golang
4abcf2066143: Already exists 
e2ea43e27ed4: Pull complete 
5d1e5825012b: Pull complete 
bd8a78f8bd68: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:cdc86d9f363e8786845bea2040312b4efa321b828acdeb26f393faa864d887b0
Status: Downloaded newer image for golang:1.22.2-alpine3.19
docker.io/library/golang:1.22.2-alpine3.19

```

**Review by alexlyp — APPROVED** [review]

**Comment by matthawkins90** [comment]
Just FYI, I'm experimenting with Podman because I just discovered that it's "generally" more secure than Docker because Podman runs without a daemon and rootless by default.

I tried `podman pull golang:1.22.2-alpine3.19` and got:
```sh
✔ docker.io/library/golang:1.22.2-alpine3.19
Trying to pull docker.io/library/golang:1.22.2-alpine3.19...
Getting image source signatures
Copying blob 4f4fb700ef54 done   |
Copying blob e2ea43e27ed4 done   |
Copying blob 5d1e5825012b done   |
Copying blob 4abcf2066143 done   |
Copying blob bd8a78f8bd68 done   |
Copying config 438d618745 done   |
Writing manifest to image destination
438d61874560e498caa4b03bc1727e96900b31e4e9d0294429a25002eb21deae
```

So it seems like the source is the same `docker.io/library/golang`, but the final image hash looks different.

**Comment by davecgh** [comment]
That is typical in my experience.  I believe its due to some compression that podman does by default which docker doesn't.

**Comment by matthawkins90** [comment]
Ah, I figured it out. Running `podman image inspect <image_id>` yields a config file that contains the digest hash:

```sh
"Id": "438d61874560e498caa4b03bc1727e96900b31e4e9d0294429a25002eb21deae",
"Digest": "sha256:cdc86d9f363e8786845bea2040312b4efa321b828acdeb26f393faa864d887b0",
"RepoTags": [
     "docker.io/library/golang:1.22.2-alpine3.19"
],
"RepoDigests": [
     "docker.io/library/golang@sha256:963da5f97ab931c0df6906e8c0ebc7db28c88d013735ae020f9558c3e6cf0580",
     "docker.io/library/golang@sha256:cdc86d9f363e8786845bea2040312b4efa321b828acdeb26f393faa864d887b0"
],
"Parent": "",
"Comment": "",
"Created": "2024-04-03T16:03:48Z"
```

**Pull request merged**
