### PR TITLE
dcrctl: fix reading from stdin in terminal mode

### LINKED ISSUE #77: Sending " - " to dcrctl in terminal mode causes it to hang
Sending the string " - " causes the terminal to hang irreversibly by sending EOF through stdin.

### PR DESCRIPTION
**Pull request by dajohi**
Fixes #77

### CODE REVIEW

**Comment by marcopeereboom** [comment]
ok

**Comment by cjepson** [comment]
My terminal still freezes on this branch, e.g. 'getbestblock -'

**Comment by marcopeereboom** [comment]
I tested this wrong.  UnOk.  This needs testing on windows cmd and powershell as well.

**Comment by jrick** [comment]
This feature doesn't work at all on windows, regardless of the console or terminal being used.

**Comment by jrick** [comment]
This pr fixes the hang for me.  Tested using fedora 24 with gnome-terminal

**Pull request merged**
