### PR TITLE
Add cmd/result interfaces for incoming new RPC command for wallet

### PR DESCRIPTION
**Pull request by alexlyp**

### CODE REVIEW

**Comment by cjepson** [comment]
We should make all updates to the JSON RPC at the same time. That is, add getwalletfee, setwalletfee, getmempoolfee, and setmempoolfee.

The command also has to be registered in dcrwalletextcmds.go
 rather than in dcrjson/walletsvrcmds.go (at the bottom).

**Comment by alexlyp** [comment]
@cjepson ok will add others as well

**Comment by davecgh** [comment]
I personally disagree with making PRs that change a lot of things at once.  In my opinion, each PR should address a specific concern.  This makes them much easier to review and accept the pieces that are good to go while the pieces that aren't continue to be worked on.

**Comment by cjepson** [comment]
@davecgh I just preferred a unified update to the JSON RPC if we're going to be prepping it for now commands relating to fees. While the RPC calls themselves take place in both daemon and wallet, the addition of the JSON backbone is just done in dcrjson.

I'm fine with it either way.

**Comment by jcvernaleo** [comment]
Had to rebase so closing manually but it is in.

**Pull request closed without merging**
