### PR TITLE
bmgr: remove block manager chain state.

### PR DESCRIPTION
**Pull request by teknico**
Port over the changes from https://github.com/btcsuite/btcd/pull/809 , see description there. Part of #709.

TODO - tests fail:
```
--- FAIL: TestHarness (0.86s)
	rpc_harness_test.go:101: unable to get nodeA's peer info
FAIL
FAIL	github.com/decred/dcrd/rpctest	2.745s
```

### CODE REVIEW

**Comment by alexlyp** [comment]
Can you resolve that test failure please?

**Comment by teknico** [comment]
I tried but I couldn't. At some point the client is shutdown and I don't know why.

**Comment by dajohi** [comment]
@teknico please rebase on master and push again.

**Comment by teknico** [comment]
Rebased on master and pushed.

**Comment by dajohi** [comment]
@teknico another rebase please.

**Comment by teknico** [comment]
Rebased on master and pushed again.

**Comment by davecgh** [comment]
This does not pass Travis.  It will be closed if that minimum level of requirement is not met.  Naturally if this one ends up getting closed, the entire chain of PRs that depend on it will also be closed.

**Comment by davecgh** [comment]
Closing this and all dependent PRs since, as mentioned in the comment above around 5 weeks ago, it doesn't pass unit tests and it hasn't been updated.

**Pull request closed without merging**
