### PR TITLE
Use correct function to fetch blocks from the blockchain for RPC

### LINKED ISSUE #406: RPC getblock returns 'Block not found' on reorgs.
When a reorg happens, a ntfn is sent to rpc client.  rpc client issues a getblock request but receives 'Block not found'

This is not a problem on v0.4.0.

### PR DESCRIPTION
**Pull request by cjepson**
Sidechain and orphan blocks were given in previous version of the
software in response to the RPC command getblock, in line with
bitcoind.  Insight relied on this functionality.  It has been
restored in 0.5.0.  Fixes #406.

### CODE REVIEW

**Comment by dajohi** [comment]
Tested and OK.

**Comment by alexlyp** [comment]
OK

**Comment by davecgh** [comment]
This change doesn't make much sense to me.  All side chain blocks should be going into the database after passing the initial sanity checks.  If that is not happening, it is a problem in the chain code.

By changing the code here in the RPC server to fetch the block from chain, you're giving up on one of the biggest benefits of the new database design -- MVCC.  With this change, you can no longer perform concurrent requests to the `getblock` RPC, and worse, when a new block is being processed due to the chain lock the entire RPC will block, which is definitely not a desirable behavior.

**Comment by cjepson** [comment]
The chain is only read-locked, so you can indeed still do concurrent calls through getblock. In fact, because it allows accession first through memory and then through the database, it should actually be substantially faster for more recent blocks except in the case that the chain lock is held.

That said, if sidechain blocks are supposed to be being written to the database but are not, that sounds like a bug introduced on merge that still needs to be addressed.

**Comment by cjepson** [comment]
Would prefer to merge if there are no further objections.

**Comment by davecgh** [comment]
This all has to change with multi-peer anyways, so even though I still don't think it's the right way to do it, it will at least allow insight to work in the mean time.

**Pull request merged**
