### PR TITLE
extend --profile cmd line option to allow interface to be specified

### LINKED ISSUE #691: --profile only takes a port number and listens on all interfaces
Like dcrwallet's --profile, I think this should take an ip:port to listen on (or :port for all interfaces).  I am unhappy when my profiler is accessible on all network interfaces.

### PR DESCRIPTION
**Pull request by jpz**
Closes #691

### CODE REVIEW

**Comment by dajohi** [comment]
I like this.  I am just wondering if the default should be to listen on localhost only...
any opinions?

**Comment by davecgh** [comment]
I agree with @dajohi.  Just like the RPC server, this should should only listen on localhost by default.  That was a big reason it only allowed a port to begin with back in the early days.

I agree with being able to specify other interfaces though as that is quite reasonable for certain setups, but it shouldn't expose your process to the world by default.

**Comment by jpz** [comment]
Thanks for the input!  I was thinking the same, but I'm conservative on breaking changes.  Is localhost or 127.0.0.1 better to use?  

My immediate inclination is to use "localhost", however by specifying "127.0.0.1" there is an in-theory small hardening in security, as hosts can be edited on several platforms - I remember in years gone by on older versions of Windows editing my hosts file a bit.

I'll go with 127.0.0.1 unless there is other feedback.

**Comment by davecgh** [comment]
Yes, `127.0.0.1` is preferred.

**Comment by dajohi** [comment]
localhost is preferred :)

**Comment by jpz** [comment]
Can you elaborate - what your the rationale for saying localhost is preferred?  

After reading through the requisite Stackoverflow reading :) the feedback seemed to be that it makes no difference unless we were opening a Unix domain socket, but this is a TCP connection.

**Comment by dajohi** [comment]
localhost will listen on ::1 as well.  Using localhost will try ::1 first, then 127.0.0.1 on systems that prefer ipv6.

**Comment by jpz** [comment]
I prefer to leave it as it is, I think connecting to 127.0.0.1 will always work, and the arguments for hardening against localhost spoofing still stand, even though it's an unlikely attack vector. Still, it's hard to foresee security issues across multiple versions of multiple operating systems.

I can just remember working in environments (old Windows NT versions) where the HOSTS file was modifiable.

I would only see a need to resolve to an IPv6 address from localhost, if I were running on a platform that doesn't support IPv4 - which is hard to imagine.

I can change it if you still think that I should however.

**Comment by jpz** [comment]
done.  thanks for the review - squashed and rebased

**Pull request merged**
