### PR TITLE
docs: Update for blockchain v5 module.

### PR DESCRIPTION
**Pull request by davecgh**
This updates the module hierarchy graphviz and module hierarchy diagram to accurately reflect the latest blockchain module dependencies.

In particular, blockchain/v5 no longer relies on the gcs, stake, or database modules.

It also rearranges the definitions a bit in the graphviz to produce a more balanced diagram.

### CODE REVIEW

**Comment by JoeGruffins** [comment]
Setting a margin on the nodes in the .gv can make them a bit more readable. The text does not bleed over the lines.
```
digraph {
	graph [splines=ortho colorscheme=svg label=<<u>Module Hierarchy</u>> labelloc=t fontsize=18.0]
	node [shape=box style="filled, rounded" margin=0.01]

```

image

**Comment by davecgh** [comment]
> Setting a margin on the nodes in the .gv can make them a bit more readable. The text does not bleed over the lines.

Are you looking at the [SVG being committed](https://raw.githubusercontent.com/decred/dcrd/7348d6433777e56a756705cb6c83090f89d3ae8c/docs/assets/module_hierarchy.svg) or generating using local tooling?

I ask because I don't see any text bleedover and I'm wondering if you're using a different layout engine.  In fact, the default margin value used by DOT (the layout engine I'm using) is more than 0.01 and as a result, using 0.01 actually makes the generated SVG (with DOT) worse.

A value of 0.1 looks good here.  Does that work for you?

**Comment by davecgh** [comment]
That's odd.  How is what I see for the original SVG I linked on FF:

image

It looks the same on chrome too.

Anyway, I updated it to include a margin of 0.1 since that seems to look for you and still looks good for me on FF, Chrome Desktop, and Chrome mobile.

**Comment by JoeGruffins** [comment]
It's really not worth wasting time over, but it looks the same for me even after the margins are changed. I don't know why. It appears setting the margin isn't the problem, it's something to do with our different `dot` builds I guess. And different vector graphics viewing interpretations? I wonder if it looks fine for others and is just me.

**Pull request merged**
