### PR TITLE
dep: sync third-party deps

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by chappjc** [comment]
Following up on slack chat, the approach is now to avoid constraints on a specific commit hash in the TOML unless absolutely unavoidable and instead use master, then update to get a commit in the lock, and review the commits for the update to that commit.  There doesn't seem to be a friendly way (from importer's perspective) of setting a specific hash in TOML.  Is this correct?

**Comment by davecgh** [comment]
I believe you're after this: https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-constrain-a-transitive-dependencys-version

All you should need is to specify in your own `Gopkg.toml` the constraint for you direct dependency and let `dep` handle the rest.

**Comment by chappjc** [comment]
@davecgh I was actually asking from the perspective of dcrd (not my software) and how it should be managing it's own dependencies.  So that link is still appropriate in that it gets to what appears to have been the problem to dcrd's own Gopkg.toml prior to this PR (that it was picking a specific revision _in the toml_ rather than letting dep handle it).

Now that four specific revisions were removed from the toml file and instead set by dep in the lock (and approved by you), it seems that an importer of both dcrd and dcrwallet packages (i.e. me) can actually use dep since the constraints no longer conflict.  Indeed, I don't get the error anymore.

No question really.  Just wanting to make sure I understand how Decred will be using dep.

**Comment by davecgh** [comment]
Ah, thanks for clarifying.  Yes, the idea is that it will only be updating the lock file with vetted commits via `dep ensure -udpate`.  The constraints on specific commits really shouldn't have been in `Gopkg.toml`, rather the lock file itself should've been edited.  Even though it says not to, it really would've been the right way to do it for the initial import to ensure the pinned commits were what they were before.

At any rate, the deps are now pinned to the current master revisions and will stay there until we specifically update them after vetting them with `dep ensure -update package/path`.

**Pull request merged**
