### PR TITLE
gcs: use dchest/siphash

### LINKED ISSUE #1394: consensus violation: Invalid regular cfilter
Moved from https://github.com/decred/dcrandroid/issues/113

[siphash.Sum64](https://github.com/aead/siphash/blob/master/siphash.go#L57) seems to be returning a wrong value for arm processors coming from [dcrd/gcs/gcs.go:96](https://github.com/decred/dcrd/blob/master/gcs/gcs.go#L96) when creating a new filter. I've tested this on both amd64 and 386 processors and they both returned the right values but fails on arm.
The following outputs were generated by inserting
``` 
fmt.Printf("siphash.Sum64(%x, %x): %v f.modulusNP: %v\n", data, key, siphash.Sum64(d, &key), f.modulusNP)
```
right at [dcrd/gcs/gcs.go:96](https://github.com/decred/dcrd/blob/master/gcs/gcs.go#L96)

ARM OUTPUT

```
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 8835029344720263971 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 11804209754276928972 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 8543490932398068092 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 4290882381034000626 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 4616478341395267308 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 2999841780892124003 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 15436574979529498528 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 4468026762970224463 f.modulusNP: 8388608
```

AMD64 OUTPUT
```
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 16770526497674945769 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 9204961670787126319 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 8543490932398068092 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 4290882381034000626 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 10250344673899768332 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 2999841780892124003 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 2466781165738763107 f.modulusNP: 8388608
siphash.Sum64([76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287 6a0cf1090000ae6c6304e52d5ddd 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac], 30a82d05a9056504051c052cdb6ef976): 8536317711245242402 f.modulusNP: 8388608
```

Same values were passed but arm got a different result.

### PR DESCRIPTION
**Pull request by dajohi**
Fixes #1394.

### CODE REVIEW

**Comment by C-ollins** [comment]
Still giving same wrong value.
`fmt.Printf("siphash.Hash(%v, %v, %x) %v = %x\n", k0, k1, d, f.modulusNP, v)`

ARM
```
siphash.Hash(316665572293978160, 8573005253291875333, 76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac) 8388608 = 341b23
siphash.Hash(316665572293978160, 8573005253291875333, 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac) 8388608 = 609dcc
siphash.Hash(316665572293978160, 8573005253291875333, 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac) 8388608 = 5b917c
siphash.Hash(316665572293978160, 8573005253291875333, 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac) 8388608 = 390f2
siphash.Hash(316665572293978160, 8573005253291875333, 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac) 8388608 = 263eec
siphash.Hash(316665572293978160, 8573005253291875333, a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287) 8388608 = 734363
siphash.Hash(316665572293978160, 8573005253291875333, 6a0cf1090000ae6c6304e52d5ddd) 8388608 = 9dfa0
siphash.Hash(316665572293978160, 8573005253291875333, 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac) 8388608 = 47574f
```

AMD64
```
siphash.Hash(316665572293978160, 8573005253291875333, 76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac) 8388608 = 30e4e9
siphash.Hash(316665572293978160, 8573005253291875333, 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac) 8388608 = 5a542f
siphash.Hash(316665572293978160, 8573005253291875333, 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac) 8388608 = 5b917c
siphash.Hash(316665572293978160, 8573005253291875333, 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac) 8388608 = 390f2
siphash.Hash(316665572293978160, 8573005253291875333, 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac) 8388608 = 1cea0c
siphash.Hash(316665572293978160, 8573005253291875333, a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287) 8388608 = 734363
siphash.Hash(316665572293978160, 8573005253291875333, 6a0cf1090000ae6c6304e52d5ddd) 8388608 = 7ba363
siphash.Hash(316665572293978160, 8573005253291875333, 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac) 8388608 = 25f022
```

**Comment by C-ollins** [comment]
ARM

```
siphash.Hash(316665572293978160, 8573005253291875333, 76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac) 8388608 = 341b23
siphash.Hash(316665572293978160, 8573005253291875333, 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac) 8388608 = 609dcc
siphash.Hash(316665572293978160, 8573005253291875333, 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac) 8388608 = 5b917c
siphash.Hash(316665572293978160, 8573005253291875333, 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac) 8388608 = 390f2
siphash.Hash(316665572293978160, 8573005253291875333, 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac) 8388608 = 263eec
siphash.Hash(316665572293978160, 8573005253291875333, a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287) 8388608 = 734363
siphash.Hash(316665572293978160, 8573005253291875333, 6a0cf1090000ae6c6304e52d5ddd) 8388608 = 9dfa0
siphash.Hash(316665572293978160, 8573005253291875333, 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac) 8388608 = 47574f
```

AMD64

```

siphash.Hash(316665572293978160, 8573005253291875333, 76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac) 8388608 = 30e4e9
siphash.Hash(316665572293978160, 8573005253291875333, 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac) 8388608 = 5a542f
siphash.Hash(316665572293978160, 8573005253291875333, 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac) 8388608 = 5b917c
siphash.Hash(316665572293978160, 8573005253291875333, 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac) 8388608 = 390f2
siphash.Hash(316665572293978160, 8573005253291875333, 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac) 8388608 = 1cea0c
siphash.Hash(316665572293978160, 8573005253291875333, a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287) 8388608 = 734363
siphash.Hash(316665572293978160, 8573005253291875333, 6a0cf1090000ae6c6304e52d5ddd) 8388608 = 7ba363
siphash.Hash(316665572293978160, 8573005253291875333, 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac) 8388608 = 25f022
```

**Comment by C-ollins** [comment]
ARM
Siphash result before the modulus is applied.
```
    siphash.Hash(316665572293978160, 8573005253291875333, 76a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac) = 7a9c546108341b23
    siphash.Hash(316665572293978160, 8573005253291875333, 76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac) = a3d0fa3ae9e09dcc
    siphash.Hash(316665572293978160, 8573005253291875333, 76a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac) = 769093bcd75b917c
    siphash.Hash(316665572293978160, 8573005253291875333, 76a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac) = 3b8c46ca9e8390f2
    siphash.Hash(316665572293978160, 8573005253291875333, 76a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac) = 40110697a4263eec
    siphash.Hash(316665572293978160, 8573005253291875333, a914d585cd7426d25b4ea5faf1e6987aacfeda3db94287) = 29a19434b4734363
    siphash.Hash(316665572293978160, 8573005253291875333, 6a0cf1090000ae6c6304e52d5ddd) = d639bb284b89dfa0
    siphash.Hash(316665572293978160, 8573005253291875333, 76a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac) = 3e019eab15c7574f
```

Siphash result using `d[1:]` instead of `d`
```
siphash.Hash(316665572293978160, 8573005253291875333, a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac) = 11373998677292870540 % 8388608 = 4deb8c
siphash.Hash(316665572293978160, 8573005253291875333, a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac) = 10149146067480999991 % 8388608 = 41f837
siphash.Hash(316665572293978160, 8573005253291875333, a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac) = 16236347657844182737 % 8388608 = c4ed1
siphash.Hash(316665572293978160, 8573005253291875333, a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac) = 11401522697196287661 % 8388608 = 7036ad
siphash.Hash(316665572293978160, 8573005253291875333, a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac) = 6407046299446449317 % 8388608 = 7c94a5
siphash.Hash(316665572293978160, 8573005253291875333, 14d585cd7426d25b4ea5faf1e6987aacfeda3db94287) = 3631195914778520850 % 8388608 = 392d12
siphash.Hash(316665572293978160, 8573005253291875333, 0cf1090000ae6c6304e52d5ddd) = 18346061237115801947 % 8388608 = 59d15b
siphash.Hash(316665572293978160, 8573005253291875333, a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac) = 16880216814950677246 % 8388608 = 35fafe
```

**Comment by davecgh** [comment]
I find it highly improbable that two different package are both producing incorrect results.  I suspect there is something else afoot in the build environment here.

**Comment by C-ollins** [comment]
I use the same build environment to generate a build for 386 processor and it works fine.

**Comment by davecgh** [comment]
What you might want to try is disabling all of the ARM and AMD64 assembler optimizations in the `siphash` package so that it runs the generic Go code on both and compare the results.

In the case of `dchest/siphash` You can do that by renaming the `*_arm.s` to `*_arm.s.bak`, `_amd64.s` to `_amd64.s.bak`, and `hash_asm.go` to `hash_asm.go.bak`, then updating the associated `.go` files (e.g. `blocks.go`, `hash.go`, `hash128.go`, etc) to remove the `!arm,!amd64` from the build constraints.

**Comment by C-ollins** [comment]
ARM
```
siphash.Hash(316665572293978160, 8573005253291875333, a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac) = 11373998677292870540 % 8388608 = 4deb8c
siphash.Hash(316665572293978160, 8573005253291875333, a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac) = 10149146067480999991 % 8388608 = 41f837
siphash.Hash(316665572293978160, 8573005253291875333, a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac) = 10248440541355244392 % 8388608 = 30fb68
siphash.Hash(316665572293978160, 8573005253291875333, a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac) = 3354336522360408795 % 8388608 = 694adb
siphash.Hash(316665572293978160, 8573005253291875333, a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac) = 6407046299446449317 % 8388608 = 7c94a5
siphash.Hash(316665572293978160, 8573005253291875333, 14d585cd7426d25b4ea5faf1e6987aacfeda3db94287) = 8143811156456440222 % 8388608 = 73019e
siphash.Hash(316665572293978160, 8573005253291875333, 0cf1090000ae6c6304e52d5ddd) = 18346061237115801947 % 8388608 = 59d15b
siphash.Hash(316665572293978160, 8573005253291875333, a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac) = 14127808489900735724 % 8388608 = 47fcec
```

AMD64
```
siphash.Hash(316665572293978160, 8573005253291875333, a9143219adce9b6f0a21fd53cb17e2fd9b2b4fac40b388ac) = 11373998677292870540 % 8388608 = 4deb8c
siphash.Hash(316665572293978160, 8573005253291875333, a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac) = 10149146067480999991 % 8388608 = 41f837
siphash.Hash(316665572293978160, 8573005253291875333, a91426fae23315d9a2e40c5b1691f891b5f6e799605b88ac) = 10248440541355244392 % 8388608 = 30fb68
siphash.Hash(316665572293978160, 8573005253291875333, a914266bfbfc65fb94e60b9bb0a6a5b95626f8a0b62988ac) = 3354336522360408795 % 8388608 = 694adb
siphash.Hash(316665572293978160, 8573005253291875333, a9140a080ab0d92a5150707ffd79c17af63cbff17c1888ac) = 6407046299446449317 % 8388608 = 7c94a5
siphash.Hash(316665572293978160, 8573005253291875333, 14d585cd7426d25b4ea5faf1e6987aacfeda3db94287) = 8143811156456440222 % 8388608 = 73019e
siphash.Hash(316665572293978160, 8573005253291875333, 0cf1090000ae6c6304e52d5ddd) = 18346061237115801947 % 8388608 = 59d15b
siphash.Hash(316665572293978160, 8573005253291875333, a9149bb0ab1ab455c220c575304aa6bb31dad3eff19888ac) = 14127808489900735724 % 8388608 = 47fcec
```

**Comment by davecgh** [comment]
Alright, so the next step here will be to create an isolated reproduction example to submit to the siphash authors.

e.g. Something like:

```Go
package main

import (
	"encoding/hex"
	"fmt"

	"github.com/dchest/siphash"
)

func main() {
	k0 := uint64(316665572293978160)
	k1 := uint64(8573005253291875333)
	d, _ := hex.DecodeString("76a9148b9502702cdbb264b2fa9fe85f34e9d2a2f3f19a88ac")

	result := siphash.Hash(k0, k1, d)
	fmt.Printf("siphash.Hash(%v, %v, %x) = %x\n", k0, k1, d, result)
}
```

Then show the results on both arm and amd64.

**Comment by C-ollins** [comment]
That snippet gave same result for both architectures

**Comment by davecgh** [comment]
So it appears to be an alignment issue in the arm assembler optimizations.  I updated the snippet again.  It should give different results now.

**Comment by C-ollins** [comment]
Tested, works fine.

**Pull request merged**
