### PR TITLE
dcrctl: fix output in --terminal mode

### LINKED ISSUE #413: dcrctl: --terminal has stopped giving clean outputs
User reporting from IRC that --terminal command responses (listunspent for instance) now looks malformed on 0.5.0

Was able to reproduce.

### PR DESCRIPTION
**Pull request by dajohi**
Fixes #413 

- [x] Test Linux
- [x] Test MacOSX
- [x] Test reading from STDIN

### CODE REVIEW

**Comment by jrick** [comment]
Issue reproduced and fix confirmed working on Fedora 24 in gnome-terminal.

**Comment by dajohi** [comment]
sendrawtransaction -
submitblock -</tmp/block.txt

**Comment by alexlyp** [comment]
tACK on debian 8

**Comment by jrick** [comment]
@dajohi appears to work correctly, both with and without --terminal mode.

**Comment by jcvernaleo** [comment]
Fixes it on OSX as well.

**Pull request merged**
