### PR TITLE
rpcserver: Set script version in raw tx results.

### PR DESCRIPTION
**Pull request by davecgh**
This ensures the recently-added script version field of `types.ScriptPubKeyResult` is set in the various RPCs that produce raw
transaction results.  Namely, `getrawtransaction`, ` decoderawtransaction`, `searchrawtransaction`, and `getblock` (with the verbose tx flag set).

Note that this is a duplicate of the `types.Vout.Version` field.

### CODE REVIEW

**Review by dnldd — APPROVED** [review]

**Review by rstaudt2 — APPROVED** [review]
Looks good to me.

It looks like the API docs also need to be updated to include the `version` field everywhere that `scriptPubKey` is referenced (maybe you are planning on doing that separately since, given the discussion around this, it sounds like you'll also be deprecating the `version` field at the output level).

Also, just a heads up, the PR title has a typo (rcpserver).

**Comment by davecgh** [comment]
@rstaudt2 Commit message updated.

Yes, I was planning to do that as part of the PR to deprecate the `version` field, but I agree that it more naturally fits here. so I'll add a separate commit to this one to include those changes later today.

**Comment by davecgh** [comment]
I've added a commit to update the JSON-RPC API docs as well.

**Comment by rstaudt2** [comment]
> I've added a commit to update the JSON-RPC API docs as well.

I reviewed the API doc updates, and those look good to me as well.

**Review by JoeGruffins — APPROVED** [review]

**Pull request merged**
