### PR TITLE
dcrctl: Remove --terminal feature

### PR DESCRIPTION
**Pull request by jrick**
The problem of securely prompting for secrets and not leaving secrets in shell
history can be solved in better ways, such as implementing a tool to read a
secret and write it back to standard output, allowing the secret to be piped to
dcrctl.  Luckily dcrctl already supports this feature!

No (official) tool exists so far, but the workflow would look like this:

```
promptsecret | dcrctl --wallet walletpassphrase - 60
```

While here removing unneeded deps from the glide files, also throw in an
unrelated dcrrpcclient dep update.

### CODE REVIEW

**Comment by jcvernaleo** [comment]
I'm totally in favor of this going in though so if anyone feels otherwise, they should probably speak up very soon.

**Comment by davecgh** [comment]
I'm in favor of this change as well.  It's already possible to use a file in the same way:

$ dcrctl --wallet walletpassphrase - 60 <passfile

**Comment by jrick** [comment]
@jcvernaleo addressed the dep update

**Comment by jyap808** [comment]
I've just upgraded and had to deal with lack of Terminal. It's pretty annoying that it's gone from a usability side of things.

**Comment by chappjc** [comment]
The `promptsecret` tool was added to help in this regard.

    promptsecret | dcrctl --wallet walletpass 0

**Comment by jyap808** [comment]
My comment was more along the lines of using the actual Terminal. It was handy to be able to up arrow last commands.

**Comment by jrick** [comment]
This isn't coming back.  The code is open source and you can maintain the patch yourself if you'd like.

Your shell has up/down functionality too you know.

**Comment by jcvernaleo** [comment]
One of the big issues we had with --terminal was that it was really bad with cross platform compatibility and we strive very hard to keep the cmd line tools as platform agnostic as possible.

**Comment by xaur** [comment]
I was using `--terminal` heavily as a REPL. Less text on the screen as there's no `dcrctl --wallet` prefix. As a bonus, after several wallet unlocks the passphrase was not leaked to shell history. Sad to see it go.

Cross platform compatibility is more important, I'll just miss this tool. Perhaps someone could wrap a simple REPL tool around dcrctl.

**Comment by jrick** [comment]
@xaur perhaps you missed my original comment, or didn't know that the promptsecret tool was added to the release (I just edited the comment to mention that it is), but you can use that.  No passphrases need to show up in shell history.

**Pull request merged**
