### PR TITLE
multi: Fix some function names in comments.

### PR DESCRIPTION
**Pull request by wanxiangchwng**

### CODE REVIEW

**Comment by davecgh** [comment]
I was going ask about the changes to `database/go.sum` that didn't look right, but I see you already updated that.

**Review by davecgh — APPROVED** [review]
Thanks for the PR.  Nice catch on the mismatched func names in the the comments.

**Comment by wanxiangchwng** [comment]
> I was going ask about the changes to `database/go.sum` that didn't look right, but I see you already updated that.

Yes, I don't know why I modified go.sum, or maybe it was my IDE that did it automatically. I have rolled back the changes.

**Comment by wanxiangchwng** [comment]
> Thanks for the PR. Nice catch on the mismatched func names in the the comments.

It's my pleasure ^_^

**Pull request merged**
