### PR TITLE
rpcserver: Remove wallet RPC stakepooluserinfo.

### PR DESCRIPTION
**Pull request by jholdstock**
Can be merged if/when decred/dcrwallet#2403 is merged.

### CODE REVIEW

**Review by davecgh — COMMENTED** [review]
Looks good.  I'll wait to approve depending on the results of the PR it depends on.

**Comment by jrick** [comment]
ticketsforaddress should also be removed.

**Comment by jholdstock** [comment]
dcrd has its own implementation of ticketsforaddress

**Comment by davecgh** [comment]
> dcrd has its own implementation of ticketsforaddress

Yeah, but he means from the `rpcAskWallet` map.  The dcrd one is in the `rpcHandlersBeforeInit` map which `rpcHandlers` is set to at init time.

**Review by davecgh — APPROVED** [review]
Looks like the requisite PR is going to be merged soon, so approving.

**Pull request merged**
