### PR TITLE
travis: drop docker

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by dajohi** [comment]
run_tests.sh returns...

**Comment by jcvernaleo** [comment]
I know it is too late since it is in but I'm a little curious as to why (and honestly disappointed) this was done.  The previous way seemed like a very good compromise between the people like @davecgh who hate containers and the people like me who hated travis errors that couldn't be reproduced locally.

**Comment by davecgh** [comment]
This was dropped for several reasons:

* Travis has to fire up a separate VM with `sudo: true` which docker requires and is much slower than the containers that launch with `sudo: false`
* It relied on having images pushed to dockerhub which requires additional permissions that only a single person had instead of simply being able to push a PR
* It relied on external setup in a separate repository that isn't the one under test
* It is yet another test dependency that makes it more complicated to work with

**Comment by jcvernaleo** [comment]
1.  While it is true that travis takes longer to start a sudo: true VM, there are speed advantages to having the docker image already setup.
2.  So add more people to the dockerhub org.  When I was there more than one person had access to it.  And generally it only ever needed changes when changing go versions which is not a very common occurances.
3.  I disagree with this.  The image in the docker hub was not being tested, it was used to run the tests.  As is there are many repos that are involved (like every go dependency) that are involved in testing and I don't see you complaining about that.
4.  In my experience (and I was the one who set it up) it made tests less complicated to work with.  The number of times there were test failures on travis only but not on anyone's dev environment was tremendous and this avoided all that.  And with the test script you were still about to run them without using docker.

I get that you do not like containers (for some reasons that I agree with and some that I disagree with) but your explanation of the situation is just not completely accurate.  Either way has pluses and minuses.  I felt I had a good compromise between your anti-container stance and my desire for completely repeatable testing.  You clearly did not agree with that.  It is your project and not mine so it gets done your way but I'd prefer things to at least be clear that there are tradeoffs doing it either way.  And I probably would have checked with the person who implemented something if they are easy to contact (and I am) before ditching it, but that might just be the way I work.

**Comment by jrick** [comment]
I just discussed this change, which i didn't agree with at the time, with dhill and the plan seems to be just removing the dcrdocker repo, and this being just a transitional change while we move the dcrd dockerfile to this repo.  Eventually we would regain the reproducible testing (and the required `sudo: true`, because travis sucks) but there would be no dcrdocker involved.

**Comment by davecgh** [comment]
For reference #1053 brings docker back, but this time with the docker files in the repo, so this is all moot.

That said, I still stand by everything I said.  As a case in point, in #1053, it takes nearly 12m with Docker versus ~9m without it.  It also took @dajohi several hours to get everything up and going with the go1.10 Docker builder image, whereas it only took a few seconds to add a line to the `.travis.yml` for it.  I firmly believe the very minor tangible benefit to using Docker here (reproducible build environment locally) simple is not worth the very clear and demonstrable downsides, as evidenced by the aforementioned increase in test time and man hours expended by @dajohi.

That is why I personally am in favor in ditching it, but since I'm not the one maintaining it and #1053 brings it back along with addressing the third concern by bringing the build environment setup (docker files) into the repo, it'll be coming back as soon as that is merged.

**Comment by jcvernaleo** [comment]
Glad to see it coming back.

As for it taking hours to update it to go1.10 that is very surprising.  It took minutes when I updated go versions in the docker images previously.  If @dajohi need help with something he could certainly have contacted me.

I think it is very wrong for you to just brush off reproducible build env as 'very minor'.

The docker images are coming back so there isn't any reason to keep discussing this but I do think you should at least consider that the other side might have some reasonable points to make and that either decision has plus and minuses rather than dismissing it as you seem to have done.

**Pull request merged**
