### PR TITLE
blockmanager: current() for testnet should check blockchain timesource.

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by jcvernaleo** [comment]
I'm running one of my testnet nodes with this patch.  Will let it go for a while.

**Comment by jcvernaleo** [comment]
This didn't cause any problems for my node running over the weekend.  No evidence that it helped though since my two nodes without it ran fine as well.
Generally I think we should limit asymmetry between mainnet and testnet when possible so I'm cool with this going in unless we have a reason to keep it.

**Comment by jcvernaleo** [comment]
Since yesterday, my nodes without this have gotten stuck on orphans twice while the node with this has stayed synced up fine.  So from my perspective, it looks like this really should go in.

**Comment by jrick** [comment]
Been running with this patch for a while now without any issues, and the patch looks fine too.  I guess it was added during early development to handle situations where no testnet blocks were received in 24 hours (which shouldn't matter anymore, and if it did, since it's testnet we can just reset it).

**Comment by jolan** [comment]
Running this on a few nodes without problems.  I agree that it is an artifact leftover from early dev and should be removed.

**Pull request merged**
