### PR TITLE
Add BlockHeight field to getstakeinfo

### PR DESCRIPTION
**Pull request by alexlyp**

### CODE REVIEW

**Comment by jrick** [comment]
block height is an int32 everywhere else.  Why the inconstancy here?

**Comment by alexlyp** [comment]
well actually in dcrd block heights are still int64s (since we skipped that sync for various reasons), so i decided to make consistent with the existing fields in getstakeinforesult.  I can change to int64 if you'd like

**Comment by jrick** [comment]
i'd use int64 here in that case.

**Comment by jcvernaleo** [comment]
Looks good to me.  I also prefer it consistant with the rest of dcr* and int64.
tACK

**Pull request merged**
