### PR TITLE
Use same fee policies across all networks.

### LINKED ISSUE #151: Unify fees for all networks
Using the same fees for all networks (mainnet, testnet, simnet, and anything else that may come later) will both simplify the code and remove gotchas when moving an application from these test networks to mainnet.  Switching these networks to use the higher mainnet fee has no monetary downside as they are not transmitting any real value.

### PR DESCRIPTION
**Pull request by jrick**
Fixes #151.

### CODE REVIEW

**Comment by jrick** [comment]
Obviously, this will need an change in wallet software as well, otherwise non-mainnet transactions will be rejected for paying too low in fees.

**Comment by chappjc** [comment]
I have about 4 testnet nodes.  How can I help with this?

**Comment by jrick** [comment]
you can help by not running it yet :)

the problem is that there are no wallets that are creating fees this high, so your node will essentially only relay blocks instead of freestanding transactions.

once the accompanying wallet change has been created, both can be tested together, and several nodes with this patch should relay transactions without any issues.

**Comment by chappjc** [comment]
That's what it sounded like. :)  I'll hold off.

**Comment by jrick** [comment]
decred/dcrwallet#235 implements the corresponding change for the wallet.

**Pull request merged**
