### PR TITLE
[WIP] Add fullticketindex skeleton

### LINKED ISSUE #777: Add RPC to query tickets as of an arbitrary block
We have an RPC to query the ticket pool at the current block but nothing exists that can query the ticket pool at an arbitrary block.  While expensive to calculate, this will be desirable for some upcoming features.

### PR DESCRIPTION
**Pull request by marcopeereboom**
Add a full ticket index that will keep all information of arriving and departing tickets.  This will become the basis for a diff version where only the changes are being stored.
 
Fixes #777

### CODE REVIEW

**Comment by matheusd** [comment]
This would also be useful to improve loading performance, as per my PRs #915 & #918 
If this index gets added, I could modify loading to use it and speed up startup time.

You could use #915 `FindSpentTicketsInBlock` on the `ConnectBlock` func and store the resulting `SpentTickets` structure on the index, as that should give you all the info you need (tickets, votes and revokes).

**Comment by davecgh** [comment]
@matheusd:

I'm fairly certain marco is going to implement this via dcrdata instead, however, to answer your question, it could not be used in an consensus critical parts of dcrd as that would make the index itself required for consensus.

**Comment by matheusd** [comment]
> it could not be used in any consensus critical parts of dcrd

Assuming the ticket index in this PR gets fully implemented and is used (hypothetically) **only** to speed up the lookup of ticket information during block validation, how would that be a consensus change?

I know that lookup is not needed (as block nodes in memory already have the ticket information), I'm just trying to wrap my head around what counts as a consensus rule change and how could the index itself become a requirement for it.

**Comment by davecgh** [comment]
Block validation is, by definition, consensus critical.  If you're making use of an index during block validation, that necessarily makes any particular quirks it may have part of the consensus rules, because any other implementations would be required to implement those quirks as well.

**Comment by chappjc** [comment]
The following PR is in support of Politeia's needs, but the newly added `TicketPool` type in `package stakedb` seems to achieve the ultimate goal of this PR:  https://github.com/dcrdata/dcrdata/pull/315
Needs polish, additional test and documentation.

**Pull request closed without merging**
