### PR TITLE
travis: Add go 1.7 and drop go 1.5 support.

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by jrick** [comment]
OK on adding 1.7

Why do we still care about 1.5?

**Comment by dajohi** [comment]
I don't.  Why vs why not?  I can remove it.

**Comment by marcopeereboom** [comment]
We shouldn't.  time to move on to 1.7. and 1.6.

**Comment by jrick** [comment]
I'm fine with removing support.  If it still works that's just a bonus but let's not keep wasting our time telling people how to build it on 1.5

**Comment by jcvernaleo** [comment]
I'm in favor of supporting current and current - 1 (so 1.7 and 1.6).

**Comment by dajohi** [comment]
Updated

**Comment by jrick** [comment]
ok

**Pull request merged**
