### PR TITLE
chaincfg, blockchain: refactor difficulty constants

### PR DESCRIPTION
**Pull request by JFixby**
#### Motivation
Currently network parameters contain multiple [unnamed numerical constants](https://en.wikipedia.org/wiki/Magic_number_(programming)#Unnamed_numerical_constants) referring conceptually to the same entities.

Example:
```
mainnetparams.go:
...
PowLimit:         mainPowLimit,// big int
PowLimitBits:     0x1d00ffff,  //conceptually the same
                               //value, but in an obscure form
...
```

The purpose of this PR is to improve code readability and maintainability.

#### Proposed changes
1) Create a structure for Difficulty
2) Group network PoW limits in dedicated variables
3) Move the `CompactToBig()` and `BigToCompact()` functions from
the ```blockchain``` to an upper-level package

#### Step 1: Create the structure ```Difficulty```

 ```Difficulty``` is a struct modeling the concept of how difficult it is to find a hash below a given target (https://en.bitcoin.it/wiki/Difficulty) ```Difficulty``` has at least three different representations:
 1) Hex string
      example: `00000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffff`
 2) big.Int
      example: `new(big.Int).Sub(new(big.Int).Lsh(bigOne, 256-32), bigOne)`
 3) Bits, or in a compact form
      example: `0x1d00ffff`

 The purpose of this struct is to properly handle all representations and to avoid creating multiple occurrences of the same constants in different forms.

All required tests are attached.

#### Step 2: Update ```mainnetparams.go```, ```simnetparams.go```, ```testnetparams.go```
Previously used `big.Int` constants are replaced to use the ```Difficulty```-struct. 

All required tests are attached.

#### Step 3: remove duplicated code from the ```blockchain``` package and update the related calls
Overall this PR moves `CompactToBig()` and `BigToCompact()` functions and related tests from the `blockchain`-package into the newly created `blockchainutil`. The reason for this is to avoid loop dependency when `chaincfg` is not able to use the functions producing the following error message:
```
go build
import cycle not allowed
package github.com/decred/dcrd
        imports github.com/decred/dcrd/blockchain
        imports github.com/decred/dcrd/blockchain/internal/progresslog
        imports github.com/decred/dcrd/dcrutil
        imports github.com/decred/dcrd/chaincfg
        imports github.com/decred/dcrd/blockchain
```
Keeping these basic functions separated improves overall code structure by making them accessible from any package in the repo, including  ```chaincfg``` and ```blockchain```.

Please let me know if additional changes are required.

### CODE REVIEW

**Comment by davecgh** [comment]
NACK.  I do not want to introduce more dependencies to `chaincfg`.  It is intended to be at the bottom of the dependency hierarchy, with the exception of hash handling.  Take a look at the `go.mod` stuff and notice this would cause a huge cascade that would effect every single package up the hierarchy chain.

**Comment by JFixby** [comment]
@davecgh I can put the new files into the `chaincfg` to avoid this and negate the last commit. Should I do it?

**Comment by davecgh** [comment]
The intent of `chaincfg` is to specify the primary constants which define the properties of the system.  They are *intentionally* constants and should not be using the chain difficulty calculation code which depends on them to create them, because that means a bug in the code would change the constants, which in turn would break consensus.  That is why you ran into the issue with the cyclic dependency.  The code is structured that way to prevent doing this very thing.

**Comment by davecgh** [comment]
I should also note, that I'm not against the notion of using a hex string over the big int calculations for the PoW limits, and in fact, I [submitted a PR a long time ago](https://github.com/btcsuite/btcd/pull/661) that did precisely that and was ultimately not approved.

**Comment by davecgh** [comment]
I would also recommend that you either open issues to discuss potential changes like this, or discuss it with devs via the dev channel in the chat platforms, as it's never fun to do work that ultimately doesn't get merged.  I've had several PRs myself that haven't been accepted, so I understand.

**Comment by davecgh** [comment]
I'm waiting from other devs to chime in as well, as I'd like to hear other's thoughts on this.

**Comment by JFixby** [comment]
Let's address the issues one by one:

#### blockchainutil-package

 `Difficulty` and `big.Int` to/from `compactInt` conversions do not belong to the Decred knowledge domain. They are actually concepts by themselves.

Thus, ideally (from the OOD point of view) they should be located in a separate package and in a separate repo, making them usable by any other network/library/tool.

Here, they are placed in the same repo in order to prevent this PR to be too radical. So the `blockchainutil`-package is a simple solution. 

I can resolve the cascade changes by cancelling third commit and keeping the duplicate code.  That is easy to fix. 

#### chain difficulty calculation

This PR from the beginning actually adds more checks for this issue and aims to prevent potential bugs with the constants.  

`Difficulty` and the related [tests](https://github.com/decred/dcrd/pull/1284/commits/b8b3651ac8854a789834fa58470ca1bde469fee0#diff-84606b0584111f2468089656665af305R35) take care of the PoW limit values consistency and their validity and the consensus rules.

#### hex-strings over big.Int

Using hex strings over bigInt as PoW limits has some pros and cons. This PR proposes to use neither of them.

PowLimit constants are not defined by [hex stings](https://github.com/btcsuite/btcd/pull/661) and are not computed from big integers (see the current dcrd code). Instead, it is proposed to use the `Difficulty`

How we create a Difficulty instance is another question. Currently there are two ways: from [hex string](https://github.com/decred/dcrd/pull/1284/commits/fe88d955bc025e3e2903e3673f2d6cae9f146877#diff-3dc7a4988cfff0e71f118dd3191162e6R59) and from [compact int](https://github.com/decred/dcrd/pull/1284/commits/fe88d955bc025e3e2903e3673f2d6cae9f146877#diff-3dc7a4988cfff0e71f118dd3191162e6R73). Some people prefer to use big.Int. This can be easily added. 

However, tecnically it doesn't matter what constructor to use, since the data structure and the [related tests](https://github.com/decred/dcrd/pull/1284/commits/fe88d955bc025e3e2903e3673f2d6cae9f146877#diff-9dc627b07a653d66c55944b3e81c523dR14) take care of it. Using hex-strings over big.Int to instantiate Difficulty is really the question of personal preferences. 

Btw, there is this [string](https://github.com/decred/dcrd/pull/1284/commits/fe88d955bc025e3e2903e3673f2d6cae9f146877#diff-3dc7a4988cfff0e71f118dd3191162e6R55) and [code](https://github.com/decred/dcrd/pull/1284/commits/b8b3651ac8854a789834fa58470ca1bde469fee0#diff-3203a6040cfe5ff98d1f499872880defR29) formatting making it human-readable and helping to spot the differences between the hex values.

**Comment by JFixby** [comment]
Also I should fix typo in the NewDifficultyFrom<s>Hash</s>HexString()

**Comment by dnldd** [comment]
Modifications being made to constants do not read any better than [what we have currently](https://github.com/decred/dcrd/blob/master/chaincfg/params.go#L28) I think. I'd add the hex representation as a helper func and keep the constants as is.

**Comment by davecgh** [comment]
I 100% disagree with you about difficulty not being part of the Decred knowledge domain.  It absolutely is part of the Decred blockchain knowledge domain because it's part of the consensus rules and both the non-compact and compact versions are one of the key determining factors for which chain ultimately is considered valid.  Those semantics are intrinsically tied to the specific resolution and characteristics.

Aside from that though, this PR also has a lot of other issues which I didn't call out due to the initial issues with attempting to introduce a new base-level dep and move the difficulty code out of blockchain where it belongs:

* It does not follow standard Go practices in terms of function naming nor the practices used throughout the dcrd codebase.  The functions should be named directly, not prefixed with `To`.  e.g. Simply `.Hex` instead of `.ToHex`
* It personally do not think it is desirable to hide the difficulty behind another custom type that is not used anywhere else in the code as it increases cognitive load and does not really provide any benefit.  This is actually something that has caused us problems in the past with the addition of `chainhash` where code assuming it was working with SHA256, so when it got changed out to blake256, it introduced bugs.  Thus, we try to avoid introducing extra custom types like this unless they provide a clear benefit, and honestly, it just doesn't here.  On the contrary, this actually introduces more opportunity for a bug.  For example, what if that big.Int in the `Difficulty` struct is switched out with a `uint256`.  It would silently and subtly break difficulty ratio calculations.  That would be much less likely to happen if the type weren't hidden behind a single-use custom type.
* I personally find the spaces in the hex string confusing and less readable as nothing else anywhere in the codebase deals with hex strings with spaces in them, and it's especially unclear why the specific spacing that is there was chosen.
* `Print` is debug code and does not belong in non-test code.  Instead, if formatting is required, it should be a `fmt.Stringer` per standard Go practices, and in that case it would probably be best to display it as hex.
* Panics are not acceptable to use for checking arguments are correct in exported library functions.  That is what errors are for.
* Almost none of the comments are consistent with the rest of the code base styling as they lack leading spaces.
* Functions have been introduced without comments which specifically goes against the [Code Contribution Guidelines](https://github.com/decred/dcrd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)

**Comment by JFixby** [comment]
@davecgh This is valuable input for me. Thank you.

Regarding knowledge domain I was trying to say that Difficulty as a concept can exist without Decred. But Decred cannot exist without Difficulty. Thus, Decred code depends on Difficulty, while Difficulty as a data structure has no reason to be aware of specific network.      

Thank you again. I will close this PR.

**Pull request closed without merging**
