### PR TITLE
config: Allow interface names for listener addresses

### LINKED ISSUE #2622: Allow listen interfaces to be configured by name, not only IP
For example, listener configurations such as these could be allowed (these are OpenBSD interface names)

```
listen=em0
listen=vio0
rpclisten=lo0
rpclisten=wg0
rpclisten=veb0
```

This should be doable by looking up an interface using https://pkg.go.dev/net#InterfaceByName, and listening on addresses returned by the `Addrs()` method.

I think it makes sense to listen on all addresses of the interface (instead of only the first) as this would easily support both IPv4 and IPv6 when an interface is configured with both.

It would be great if interface tags were supported as well (e.g. the interface with the default route is tagged "egress" on OpenBSD) but I don't see a straightforward way to do this using the Go standard library.

### PR DESCRIPTION
**Pull request by jrick**
This allows --listen and --rpclisten config options to specify
interface names, instead of only exact IP addresses.  If an interface
is named, all IP addresses associated with the interface during config
parsing will be added to the normalized listeners.

Closes #2622.

### CODE REVIEW

**Comment by jrick** [comment]
This isn't working for IPv6 link-local addresses.

```
2021-03-15 11:35:43.705 [WRN] SRVR: Can't listen on [fe80::1]:19108: listen tcp6 [fe80::1]:19108: bind: can't assign requested address
```

The listen address must include the zone.  For example, this listener works:

```
$ dcrd --testnet --listen=fe80::1%lo0
...
2021-03-15 11:38:29.808 [INF] CMGR: Server listening on [fe80::1%lo0]:19108
```

There also should be a way to change the port that will be listened on, instead of only supporting the default port.  I'm not sure what syntax should be used for this.

**Review by dnldd — APPROVED** [review]

**Comment by dnldd** [comment]
I got this in testing:

```
❯ dcrd --rpcuser=user --rpcpass=pass --profile=127.0.0.1:2555 --appdata=/home/dnldd/mh/node --datadi
r=/home/dnldd/mh/node/data --debuglevel=info --listen=wlp2s0 --listen=lo --listen=127.0.0.1:9108 --t
xindex --addrindex                                                                                  
listeners are: ([]string) (len=4 cap=5) {                                                           
 (string) (len=18) "192.168.100.6:9108",                                                            
 (string) (len=32) "[fe80::ddaa:db81:2421:a1b1]:9108",                                              
 (string) (len=14) "127.0.0.1:9108",                                                                
 (string) (len=10) "[::1]:9108"                                                                     
}            

...


2021-03-15 15:58:27.843 [WRN] SRVR: Can't listen on [fe80::ddaa:db81:2421:a1b1]:9108: listen tcp6 [f
e80::ddaa:db81:2421:a1b1]:9108: bind: invalid argument   
```

Seems fine for ipv4, regarding the warning I do not have an ipv6 address so can't confirm there is an issue with that.

**Comment by jrick** [comment]
Yeah, see my comment above.  fe80::/10 is a link local network, so that will need the zone appended.

Even if you don't have IPv6 connectivity to the internet, your interface is still configured with that link-local address, and dcrd should still listen on it.

**Comment by dnldd** [comment]
Can confirm I'm no longer getting the ipv6 related warning with the updated PR.

**Comment by jrick** [comment]
This is also affecting options like --connect which also use the address normalization, and I'm not sure if we really want that behavior.  At the very least, with --connect, if an interface is going to be allowed, it should maybe only use the first address, and not all of them.  I'm wondering what others think should be done for these options.

**Comment by dnldd** [comment]
Yeah for `--connect` it'd b better to only normalize just the addresses specified only. We probably need a parameter for `normalizeAddresses` to toggle when to get interface addresses or not.

**Review by davecgh — APPROVED** [review]
We've tested the listen and connect functionality works as intended on OpenBSD, Mac, Linux, and Windows.

I also sanity checked the RPC `node connect` works as intended on Windows and Linux.

**Pull request merged**
