### PR TITLE
Add a checkpoint for block 24480

### PR DESCRIPTION
**Pull request by cjepson**

### CODE REVIEW

**Comment by chappjc** [comment]
tACK mainnet:

```
[INF] CHAN: Verified checkpoint at height 440/block 0000000000002203eb2c95ee96906730bb56b2985e174518f90eb4db29232d93
[INF] BMGR: Downloading headers for blocks 441 to 24480 from peer decred.monkeyland.io:9108
[INF] BMGR: Verified downloaded block header against checkpoint at height 24480/hash 0000000000000c9d4239c4ef7ef3fb5aaeed940244bc69c57c8c5e1f071b28a6
[INF] BMGR: Received 24040 block headers: Fetching blocks
```

And then the usual processing of blocks.... I guess I thought this would accelerate this process, but it's about the same.

**Comment by alexlyp** [comment]
tACK

**Comment by alexlyp** [comment]
@chappjc I've noticed a pretty hefty sync speed increase with this and #189 

Things will still be relatively slow for sync until we get in the other upgrades in btcd.  But hopefully those will be in soon (with @davecgh speeding along with the sync)

**Comment by chappjc** [comment]
@alexlyp I don't have #189.  Perhaps that's the difference.

**Pull request merged**
