### PR TITLE
Remove btcsuite artifacts and adjust links.

### PR DESCRIPTION
**Pull request by frankbraun**
Seems like they have been overlooked.

### CODE REVIEW

**Comment by jcvernaleo** [comment]
@frankbraun Looks good, thanks!

One minor thing.  Generally we like to squash related changes to a single commit before they go in to keep the history easier to read.  In this case I just did the squashing for you since it was easier enough.

Thanks!

**Comment by jcvernaleo** [comment]
This was merged in as 1e22c04

**Comment by frankbraun** [comment]
@jcvernaleo thanks for merging!

OK, I will adhere to that next time.

**Comment by jcvernaleo** [comment]
@frankbraun for the record, I really appreciate these doc fixing PRs.  I really hate incorrect docs in code (and tried very hard to fix these things myself before release but just did not have the time to get it perfect).

**Comment by frankbraun** [comment]
OK, then I'll hit you with a few more. I'm trying to wrap my head around the Decred code base and when I see stuff like this it triggers my OCD :smile:

**Pull request closed without merging**
