### PR TITLE
Add consolidate cmd and response framework to the JSON RPC

### PR DESCRIPTION
**Pull request by cjepson**
This adds the consolidate command to master, enabling a wallet to
consolidate small UTXOs into a large UTXO.

### CODE REVIEW

**Comment by alexlyp** [comment]
tACK along with corresponding dcrwallet PR

**Comment by jcvernaleo** [comment]
Needs a rebase but then OK

**Comment by cjepson** [comment]
Rebased, added optional account in JSON cmd

**Comment by jrick** [comment]
ok

**Pull request merged**
