### PR TITLE
peer: Do not expect a response to mempool or getminingstate requests.

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by JasonSome** [comment]
What about that? Simple dcrd clients should be able to request the whole of a node's mempool and get an actual response, not be ignored.

**Comment by alexlyp** [comment]
@JasonSome that is not what this PR accomplishes.  This makes it so you don't disconnect from a peer when they don't respond from certain messages.  (mempool, getblocks and miningstate)

**Comment by dajohi** [comment]
This PR changes dcrd to not require a response for certain p2p messages.

**Comment by alexlyp** [comment]
Appears to help from disconnecting due to stalled message responses from peers.
tACK

**Comment by cjepson** [comment]
OK

**Comment by jrick** [comment]
I disagree with this change because it's far worse for your node to completely fail because your sync node becomes unresponsive than to randomly kick good peers that take a little longer than expected.

A better workaround until we get multipeer syncing would be to have a different stall detection ruleset for the syncpeer vs other peers.  If your syncpeer sucks it should be punted.  Other peers don't matter as much and it would be beneficial to the network to keep them connected longer.

**Comment by marcopeereboom** [comment]
This is now tracked in #776

**Pull request closed without merging**
