### PR TITLE
[WIP] feature/dcrd mobile#938

### LINKED ISSUE #938: DCRD spv - mobile bindings
dependency: https://github.com/decred/dcrwallet/issues/1000

decred/dcrd

- [ ] Include an explicit travis job to generate an iOS library based on a specific package and to deploy its spec to Cocoapods
- [ ] Include an explicit travis job to generate an Android library and to deploy the archive
- [ ] Create a package (Ex: mobile) that includes a node representation(wrapper type) that exports the necessary methods for the wallet.

decred/decrediton mobile

- [ ] Create a react native module that encapsulates all the bindings(methods).

### PR DESCRIPTION
**Pull request by rgeraldes**
WIP - PR Fixes #938 

**Pre-Requisites:**

_IOS - cocoapods_

- sign up for an account with your email address (reference: https://guides.cocoapods.org/making/getting-setup-with-trunk.html)

- get the authentication Token from the password field of ~/.netrc

- define a secure variable (pod relies on COCOAPODS_TRUNK_TOKEN) - that will store the token - in the repository settings(dcrd). (reference: https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings)

Other:
- complete the cocoapods spec license fields (file: template.podspec)

_Android - maven central_

- create a Sonatype account (reference: http://central.sonatype.org/pages/ossrh-guide.html#SonatypeOSSMavenRepositoryUsageGuide-2.Signup)
- request permissions to upload artifacts on Maven Central:
 (Ethereum example: https://issues.sonatype.org/browse/OSSRH-25355)
- Define the following secure variables in the travis repository settings(dcrd):
        - SONATYPE_USERNAME
        - SONATYPE_PASSWORD
With your username and password being the same ones you used to create the Jira issue. To confirm your credentials are right, you can try using them to login at http://oss.sonatype.org.
- generate a PGP key (reference: http://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/) - The PGP key is needed to be able to sign the artifacts before the upload to Maven Central.
- define a secure variable ($PGP_KEY) in the travis repository settings(dcrd), just like the auth token step done for iOS. Display value in build log set to off > secure value.

Other:
- complete the pom file license information (file:mobile/build/pom.xml)

**Integration with Decrediton Mobile**

_iOS - automatic dependency (Cocoapods)_ 

1. adding pods to an existing xcode project (reference: https://guides.cocoapods.org/using/using-cocoapods.html)
2. edit podfile - include dcrd dependecy

```
target 'MyApp' do
  pod 'Dcrd', '~> 3.0' # Example
end
```
_Android - automatic dependency (Maven central)_

1. Edit build.gradle - Android's folder

```
repositories {
    mavenCentral()
}

dependencies {
    // All your previous dependencies
    compile 'org.decred:dcrd:1.0' // latest release
}
```

### CODE REVIEW

**Comment by dajohi** [comment]
Hi @rgeraldes -
How is this different that from using https://godoc.org/golang.org/x/mobile/app?

**Comment by rgeraldes** [comment]
Hi David, 

1
You can either create a library or a native app with gomobile. I'm just familiar with library side (gomobile bind).
Decred's use case requires a library, since the app will be done in react native(afaik) in order to re-use some of decrediton's components. The end goal is to provide a react native module (ex: Node) that encapsulates all the methods available in the library.

2
Context

**First task - (CI) generate artefacts**

I've been doing this task. It's independent from the SPV topic. 

**The second task - create a node representation (library)**

The second task relies on the spv node. 
The overall plan is to have dcrwallet has the base of our client library. This is something that I need to confirm with Decred team. This might introduce some problems since I need to check if it's possible to run two programs(wallet + dcrd) on a mobile context. Also, the app stores usually have strict guidelines. If the plan is to re-use dcrwallet logic, this PR's files will be moved to dcrwallet, since it's going to be the base of our mobile client library.
I haven't seen the spv implementation, but the interaction between dcrd and the wallet should be maintained also for spv, since most of the operations can still be done, and switching between the full and light mode should be simple.

**Comment by jrick** [comment]
spv will live entirely within dcrwallet -- there's no need to add mobile support to dcrd, and it would create an awful experience to try and run dcrd on mobile devices (and is probably not possible in the first place due to background task restrictions)

**Comment by rgeraldes** [comment]
thanks for the input @jrick. @raedah passed me that info some moments ago.
That's good news. The idea of running a full node was just to test the full stack, not for the experience itself.

**Comment by rgeraldes** [comment]
I'm going to move this issue to dcrwallet

**Pull request closed without merging**
